export interface MissionData {
  date: string;
  title: string;
  role: string;
  scanId: string;
  objective: string;
  tactics: string[];
  outcome: string;
  status: string;
  statusColor: string;
  align: 'left' | 'right';
  isShield?: boolean;
  isGhost?: boolean;
  imageUrl?: string;
}

export const missions: MissionData[] = [
  {
    date: '2024.Q3 — 2025.Q1',
    title: 'Operation: Prague.Wedding',
    role: 'Software Engineer, Front-End',
    scanId: 'PW-OPS-24',
    objective:
      'Design and deliver a professional marketing and booking website for a Prague-based wedding coordinator — enabling couples across four language markets to discover service packages, explore a gallery, and submit inquiries. Built as a zero-backend React SPA with version-controlled multilingual content, serverless form handling, and a full international SEO layer including hreflang routing and geolocation metadata.',
    tactics: [
      'Built a React 19 + TypeScript SPA with React Router 7 and Vite 6 — delivering a rich single-page experience across home, blog listing, and dynamic blog post routes with a sticky collapsing header and mobile hamburger menu with body scroll lock.',
      'Implemented a four-language i18n system (Ukrainian, English, Czech, Russian) — all content version-controlled in a single translations.ts, language persisted via localStorage and URL query param, with dynamic SEO meta/OG/hreflang tag updates on every language switch.',
      'Crafted interactive service tier cards with tab-style navigation and scale/translate animations; built a multi-state contact form (idle → submitting → success/error with 5s auto-close) powered by Web3Forms API for serverless submission — zero backend or server infrastructure required.',
      'Delivered a comprehensive SEO layer: Open Graph, Twitter Card, geolocation tags with Prague coordinates, sitemap, and robots.txt — targeting international couples searching for Prague wedding services in four languages.',
      'Built a version-controlled blog system with multilingual post content and slug-based routing — no external CMS, no database, no API; bundled GDPR cookie consent modal and Privacy Policy overlay for EU compliance.',
    ],
    outcome: '4-LOCALE ZERO-BACKEND',
    status: 'ONGOING',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'left',
    imageUrl: 'images/pwc.avif',
  },
  {
    date: '2022.Q2 — 2026.Q1',
    title: 'Operation: TW-BSCI',
    role: 'Software Engineer, Full-Stack',
    scanId: 'TW-BSCI-24',
    objective:
      'Engineer features across the microservices platform powering end-to-end bioscience e-commerce — spanning Ruby/Rails business logic and React frontends. Deliver real-time order tracking across 10+ specialized WebSocket channels and sustain a multi-stage order pipeline (Draft → Quote → Checkout → Batch → Fulfillment) for gene synthesis, IgG antibodies, NGS, and custom vector products.',
    tactics: [
      'Extended the Rails 6.1 ecommerce-infrastructure service — contributing business logic, MongoDB/Mongoid data models, Sidekiq job orchestration, and 10+ specialized ActionCable + Ably WebSocket channels (checkout, genes, IgG, NGS, designer) for real-time order status delivery.',
      'Architected Ruby on Rails API extensions and public endpoints to power a highly customized, per-order production pipeline across 24x7 operations.',
      'Optimized MongoDB query layers and Sidekiq job orchestration to sustain throughput under variable, high-complexity order loads.',
      'Delivered full-stack features on a React/Redux SPA (S3 + CloudFront), extending order configurators for custom genes, oligo pools, and NGS enrichment panels.',
      'Delivered React features across three frontend surfaces — main customer portal (ecommerce-client) and SOX-compliant dedicated checkout (ecommerce-checkout-frontend) — consuming a shared Radix UI design system for consistent cross-service component delivery.',
      'Maintained cross-service contract integrity using Pact consumer-driven contract tests; contributed to multi-language test coverage (Minitest, Pytest, Jest) alongside OpenTelemetry tracing, NewRelic APM, and Sentry error tracking across the full service mesh.',
    ],
    outcome: '-50% TECH DEBT',
    status: 'COMPLETED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'right',
    imageUrl: 'images/tw-bsci-01.webp',
  },
  {
    date: '2021.Q3 — 2025.Q1',
    title: 'Operation: Seeking Alpha',
    role: 'Software Engineer, Back-End',
    scanId: 'SA-OPS-22',
    objective:
      'Operate within a mature, large-scale Rails 7.0 monolith powering seekingalpha.com — a market-leading financial content and investment research platform serving millions of active investors across web and mobile. Navigate 505 models, 684 controllers, and 226+ background jobs to deliver features across content publishing, subscription management, financial data tooling, and community — with zero tolerance for downtime or latency across three subscriber tiers (Free, Premium, PRO).',
    tactics: [
      'Extended Rails 7 backend APIs serving web and native mobile clients (iOS/Android) — implementing JWT authentication, Pundit RBAC policies for tiered subscriber access, and push notification pipelines via RPush.',
      'Optimized multi-layer query strategies across a dual-database stack (MariaDB 10.6 + PostgreSQL 13) with Elasticsearch 8 and Sphinx search, achieving low-latency delivery of financial articles, earnings transcripts, and analyst research at peak traffic loads.',
      'Leveraged Redis 7 caching, Fastly CDN page caching, and Resque background job orchestration (226+ workers) to sustain high-concurrency throughput across stock screeners, ETF analytics, dividend tracking, and earnings calendar data.',
      'Contributed to payment and subscription infrastructure integrating Stripe, Braintree, and Zuora — covering author research bundle subscriptions, iOS/Android in-app purchases, and editorial content monetization workflows.',
      'Shipped within a multi-integration production environment: GitHub Actions + Jenkins CI/CD, Brakeman security scanning, RuboCop quality enforcement, and observability via Datadog + Rollbar + Logstash across AWS (S3, SNS, Athena, CloudSearch).',
    ],
    outcome: 'MILLIONS UNITS SERVED',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'left',
    // isShield: true,
    imageUrl: 'images/seeking-alpha.avif',
  },
  {
    date: '2021.Q1 — 2022.Q3',
    title: 'Operation: Payment Modals',
    role: 'Founding Partner, Full-Stack Engineer',
    scanId: 'PM-OPS-20',
    objective:
      'Co-found and architect a self-serve SaaS platform enabling businesses to design fully branded Stripe payment modals and embed them on any website via a single script tag — no backend, no friction. Sole technical architect and engineer, responsible for end-to-end delivery of the product, admin infrastructure, and marketing surface. Go-live target: five minutes from signup to first payment collected.',
    tactics: [
      'Engineered an interactive modal designer with live preview — allowing non-technical users to configure branding, copy, colors, and imagery without writing a single line of code.',
      'Built a visual Stripe checkout form builder with full support for custom images, bespoke copy, and both recurring and one-time payment modes.',
      'Delivered a zero-friction embed model: businesses inject a single generated script tag to activate a fully hosted, production-ready payment modal on any website in under five minutes.',
      'Implemented end-to-end encryption of sensitive Stripe credentials and configuration data to meet security compliance requirements across all tenants.',
      'Architected and shipped the complete product surface — marketing site, admin panel, and REST API — from concept to live product as founding technical partner.',
      'Integrated GPay, ApplePay and PayPal payment methods — enabling businesses to accept payments through these popular payment methods without requiring additional technical expertise.',
    ],
    outcome: '5 MIN TO REVENUE',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'right',
    imageUrl: 'images/pm1.avif',
  },
  {
    date: '2019.Q1 — 2022.Q1',
    title: 'Operation: The Skills',
    role: 'Lead Solution Engineer',
    scanId: 'SK-OPS-19',
    objective:
      'Architect and ship a video-based sports education platform from the ground up — enabling world-class athletes (Phelps, Rapinoe, Sharapova, White and more) to deliver elite coaching at scale to youth and amateur athletes globally. Operating as lead engineer in a fully remote team of four, with end-to-end ownership across API, admin panel, customer SPA, marketing site, and mobile payment flows.',
    tactics: [
      'Designed modular system architecture (Rails REST API, ActiveAdmin panel, NextJS marketing site, React customer app) — cutting maintenance time and cost by 27%.',
      'Built JWT-based auth with OAuth integrations for Google, Facebook, and Apple across web and mobile; integrated Brightcove for scalable video content delivery.',
      'Integrated Stripe, PayPal, and native Apple/Android In-App purchase pipelines — increasing paid conversion funnel by 7%.',
      'Delivered Postgres + Redis data storage architecture; achieved 83% test coverage and 100% Swagger API documentation across all endpoints.',
    ],
    outcome: '+7% FUNNEL GAIN',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'left',
    imageUrl: 'images/theskills.webp',
  },
  {
    date: '2019.Q3 — 2020.Q2',
    title: 'Operation: 123',
    role: 'Software Engineer, Full-Stack',
    scanId: 'VC-OPS-19',
    objective:
      'Engineer a subscription-driven vanity URL management platform for the Swiss market — enabling businesses and individuals to register memorable keywords that redirect to destination URLs. Own end-to-end technical delivery: keyword lifecycle engine, payment pipeline, Angular SPA, and production infrastructure — with zero tolerance for redirect downtime or stale state.',
    tactics: [
      'Architected a hybrid Rails JSON API + Angular 5 SPA — Rails serves the application shell and exposes typed endpoints; Angular handles all modal-driven user flows with real-time keyword availability checking, including pending-payment collision detection.',
      'Built a full keyword lifecycle engine (inactive → pending → active → expired) across eight subscription tiers from 1-day to 10-year — with Delayed Job handling async expiration and auto-cleanup of stale pending records within 2-minute SLA windows.',
      'Integrated ThriveCart webhook pipeline to drive atomic payment state transitions — covering approval, refund, cancellation, and renewal events — with a dedicated PaymentProcessor/ThriveProcessor service layer abstracting all gateway logic.',
      'Implemented Devise + Petergate RBAC for tiered user/admin access; wired Mandrill transactional email across the full subscription lifecycle; instrumented per-keyword click analytics with bot filtering.',
      'Deployed via Capistrano + Docker to an Apache/Puma stack with SSL termination, Zurich-timezone business logic, and environment-scoped secrets for Mandrill, ThriveCart, and MySQL credentials.',
    ],
    outcome: '8 TIERS LIVE',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'right',
    imageUrl: 'images/123.avif',
  },
  {
    date: '2020.Q1 — 2020.Q3',
    title: 'Operation: BVP',
    role: 'Software Engineer, Full-Stack',
    scanId: 'BAV-OPS-19',
    objective:
      'Architect and deliver a compliant, multi-portal corporate pension management system connecting three distinct user groups — DUK employees, AUPU employees, and HR managers — each operating on isolated subdomains with purpose-built access patterns. Primary directives: eliminate credential storage through passwordless auth, enforce postal identity verification, and synchronize bulk insurance records from an external Prequity system without disrupting live operations.',
    tactics: [
      'Architected a domain-constrained multi-portal Rails 5.2 application — three independent SPA surfaces (DUK employee, AUPU employee, Employer) routed via subdomain constraints at the routing layer, each with fully isolated auth flows and access controls.',
      'Implemented passwordless employee authentication via email sign-in tokens backed by a three-stage registration state machine (STARTED → EMAIL_CONFIRMED → COMPLETED) — eliminating credential storage entirely across the employee-facing portals.',
      'Built a postal identity verification pipeline — activation codes generated as print-ready PDF letters via Prawn and physically mailed to employees, required before account activation can complete.',
      'Engineered Prequity bulk synchronization: ~2,000-record CSV batches of insurance holders, contracts, and documents imported via SmartCSV + ActiveRecord::Import with batch-safe upsert logic and staging email interception to prevent environment bleed.',
      'Delivered React 16 + Apollo GraphQL registration flows with Formik validation — contract numbers, email, and DOB validated via GraphQL before submission; PostgreSQL full-text search (PgSearch) powering HR manager employee lookup with Pagy pagination.',
    ],
    outcome: '3 PORTALS DEPLOYED',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'left',
    imageUrl: 'images/bv.avif',
  },
  {
    date: '2020.Q3 — 2021.Q2',
    title: 'Operation: KEFIR',
    role: 'Software Engineer, Full-Stack',
    scanId: 'KP-OPS-20',
    objective:
      'Design and deliver a field operations management system for — a major construction and insulation contractor — bridging internal staff and Gunvor subcontractors through structured order tracking, measurement recording, and financial reporting. Mandate: replace manual billing workflows with a role-enforced digital pipeline capable of generating audit-grade SAR and GAR financial reports on demand.',
    tactics: [
      'Architected a Rails 5.2 + React 16/Stimulus hybrid — Turbolinks-backed server rendering for core navigation with React components handling flexible measurement forms and part lists backed by PostgreSQL hstore and JSONB for schema-free field data.',
      'Built a real-time budget utilization engine — orders tracked against defined spend thresholds with 80% warning and 90% critical indicators, giving project managers continuous visibility over active construction budgets.',
      'Implemented Pundit role-based authorization across four access tiers (admin, staff, gunvor, sophisticates_admin) — enforcing granular resource policies on all order, measurement, collection, and reporting actions.',
      'Delivered a dual-format export pipeline: SAR and GAR financial reports generated as print-ready PDFs via Prawn/Prawn-Table; Excel exports via rubyXL — covering the full invoicing and audit trail for construction billing cycles.',
      'Integrated iScala ERP product catalog with JSONB-tracked historical article pricing and measurement-level surcharge calculations; deployed via GitLab CI/CD with parallel RSpec + Capybara test stages and auto-deploy to Kubernetes review environments on feature branches.',
    ],
    outcome: 'SAR + GAR AUTOMATED',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'right',
    imageUrl: 'images/kfr.avif',
  },
  {
    date: '2018.Q3 — 2019.Q2',
    title: 'Operation: M-Power',
    role: 'Software Engineer, Full-Stack',
    scanId: 'MP-OPS-18',
    objective:
      'Architect and deliver a competition lifecycle management platform for trade chambers — orchestrating browser-based game competitions across a four-tier organizational hierarchy, from chamber setup through live game session tracking to certificate generation. Bridge between hierarchical school and chamber management and an external game client, with cryptographically validated scoring to eliminate result tampering.',
    tactics: [
      'Designed a four-tier STI group hierarchy (Admin → Chamber → Institution → Cohort) using Rails Single Table Inheritance — with Pundit policies enforcing role-specific visibility and management rights at every organizational boundary.',
      'Built a game session API (POST /api/attempts to initialize, PUT /api/attempts/:token to submit) with MD5 checksum validation on every score submission, preventing client-side manipulation across all active contests.',
      'Implemented team token/password authentication for game client access; integrated Devise Invitable for teacher-to-student invitation flows and cohort self-enrollment via shared registration tokens.',
      'Delivered PDF certificate generation per team via Prawn and Excel statistics exports via RubyXL, covering leaderboards aggregated by chamber, institution, and level — with teacher test mode enabling out-of-competition trial runs even when a contest is inactive.',
      'Containerized with Docker + Docker Compose; deployed via Capistrano + Ansible; instrumented with Sentry and AppSignal for production error tracking and APM across the full competition lifecycle.',
    ],
    outcome: 'TAMPER-PROOF SCORING',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'left',
    imageUrl: 'images/mp.avif',
  },
  {
    date: '2018.Q1 — 2018.Q4',
    title: 'Operation: MN-Desk',
    role: 'Software Engineer, Full-Stack',
    scanId: 'MND-OPS-18',
    objective:
      'Operate as a contributing engineer on a large-scale, multi-tenant SaaS news distribution platform — serving press offices, journalists, and organizations across 16 language markets and international subdomains. Navigate and extend a battle-hardened Rails monolith (167 models, 53 background workers, 71 service objects) with microservice extensions, high-throughput async pipelines, and integrations spanning social networks, CRMs, analytics platforms, and CDNs.',
    tactics: [
      'Delivered features across the publish, network, analyze, and report namespaces of the Rails 5.2 monolith — contributing to press release management, multi-tenant hosted newsrooms, and audience analytics surfaces used by media organizations globally.',
      'Built and maintained Grape REST API endpoints powering third-party newsroom integrations; extended multi-channel social distribution pipelines across Twitter, Facebook, LinkedIn, Instagram, and YouTube with consistent delivery guarantees.',
      'Worked within the Sidekiq Pro ecosystem (53 background job types, sidekiq-cron) to sustain async press release distribution, media monitoring ingestion from Twingly and GNIP, and SendGrid email delivery under high-volume publishing loads.',
      'Drove Elasticsearch 6.5 query improvements as part of the ongoing migration from deprecated Solr 4.10 — optimizing content search across multi-locale newsroom content at scale, with Redis and Memcache as layered caching layers.',
      'Shipped within a Buildkite CI/CD pipeline with Heroku review apps and an RSpec + VCR + Percy visual regression test suite; integrated across Stripe, Salesforce, HubSpot, Segment, S3, and Cloudinary.',
    ],
    outcome: '16 MARKETS SERVED',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'right',
    imageUrl: 'images/mnd.avif',
  },
  {
    date: '2019.Q1 — 2019.Q4',
    title: 'Operation: NJ-SIGN',
    role: 'Software Engineer, Full-Stack',
    scanId: 'NS-OPS-19',
    objective:
      'Extend and harden a Japanese-market digital signature and contract management platform — delivering secure multi-party document workflows from template creation through blockchain-anchored approval. Scope covers a full document lifecycle state machine, KMS-encrypted S3 storage, polymorphic digital signature placement, and multi-OAuth integrations with Google, Slack, and Auth0.',
    tactics: [
      'Engineered a document lifecycle state machine (init → draft → in_progress → approved/rejected → trashed) across multi-user team workspaces — with owner/signer role-based access, subscription plan gating (free/lite/pro) on max contracts and workflow features, and hierarchical folder structures per team.',
      'Implemented polymorphic digital signature placement on both DocumentItem and TemplateItem models; built guest signer access via time-limited tokens and per-document password protection for secure external signing flows.',
      'Built a multi-stage PDF processing pipeline — document generation via Prawn, merging via CombinePDF, Word-to-PDF conversion via LibreOffice — and executed live S3 migration from Google Drive with AWS KMS encryption for document-at-rest security.',
      'Wired Sidekiq + Redis background workers across document mailers (creation, approval, confirmation), blockchain hash recording for finalized contracts, Google Docs processing, and document sharing notifications — sustaining async reliability across all lifecycle events.',
      'Integrated multi-provider OAuth (Google Drive import/export + native Docs support, Slack channel document sharing, Auth0) via OmniAuth; instrumented the ShareLog audit trail for full document distribution history and Sentry APM for production monitoring.',
    ],
    outcome: 'BLOCKCHAIN-ANCHORED',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'left',
    imageUrl: 'images/njs.avif',
  },
  {
    date: '2018.Q4 — 2019.Q2',
    title: 'Operation: Sophisticate',
    role: 'Software Engineer, Front-End',
    scanId: 'SOPH-OPS-19',
    objective:
      'Design and deliver a high-performance static marketing and portfolio site for a digital strategy consultancy — showcasing services, team, and client case studies. Built on Gatsby v2 with a file-based content model, animated transitions, and PWA offline support; containerized and deployed to Kubernetes via GitLab CI/CD with zero CMS or database dependency.',
    tactics: [
      'Built a Gatsby v2 static site with React 16 — GraphQL data layer querying Markdown/YAML frontmatter for all content, gatsby-image + Sharp for responsive optimized image delivery, and Reactstrap/Bootstrap 4 for UI scaffolding.',
      'Implemented animated page transitions with direction tracking and keyboard navigation between project pages (← / → arrow keys) — enabling fluid, app-like case study browsing on a static site.',
      'Authored custom Markdown components (<reco>, <left>/<right>, <process>) allowing editors to compose rich testimonial, two-column, and step-list layouts within flat Markdown files — eliminating any CMS or database dependency.',
      'Delivered a project theming system with radial gradient color palettes (rot, orange, grün, türkis, markenblau) applied dynamically to case study cards; wired PWA offline caching for instant repeat visits.',
      'Containerized via multi-stage Docker build (Node 10 build → Nginx Alpine) and deployed to staging and production Kubernetes environments via Helm through GitLab CI/CD.',
    ],
    outcome: 'ZERO-CMS DELIVERED',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'right',
    imageUrl: 'images/sfts.avif',
  },
  {
    date: '2019.Q3 — 2020.Q2',
    title: 'Operation: Volt',
    role: 'Software Engineer, Full-Stack',
    scanId: 'VLT-OPS-19',
    objective:
      'Deliver features and integrations across a multi-application fintech monorepo — spanning a Rails JSON API backend, Ember.js borrower portal, and React admin dashboard — serving student loan borrowers, employer partners, and platform administrators. Navigate complex financial domain models: loan lifecycle state machines, SOAP payroll integrations, double-entry accounting via a general ledger, and enterprise SAML SSO for institutional partners.',
    tactics: [
      'Extended the sl-pay Rails 5.2 backend across dual versioned APIs (/api/v1, /api/v2) — implementing Devise + JWT auth, SAML SSO for enterprise partners (Citizens, John Hancock, Prudential), and AASM state machines for loan and payment lifecycle with Paper Trail audit logging.',
      'Built SOAP-based payroll system connectors (JH/EPS/iPay) and Finicity financial data aggregation pipelines — bridging employer payroll data into disbursement workflows alongside NSLDS student loan data synchronization.',
      'Contributed to the Ember.js 3.8 customer portal — implementing loan dashboard features, income-driven repayment flows, PSLF eligibility tools, and document e-signing with partner-specific multi-tenant theming per institutional brand.',
      'Extended the React 16 + Redux/Redux-Saga admin dashboard — delivering employer/employee management surfaces, invoice generation, and bulk operation interfaces built on Material-UI and DevExtreme data grids.',
      'Maintained Sidekiq background job pipelines for email, reports, and batch processing; instrumented Sentry and LogRocket across all three applications; shipped via CircleCI with Docker and S3 + CloudFront deployments.',
    ],
    outcome: '3-APP FINTECH STACK',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'left',
    imageUrl: 'images/vlt.avif',
  },
  {
    date: '2019.Q4 — 2020.Q3',
    title: 'Operation: SecureAuth',
    role: 'Team Lead | Software Engineer, Full-Stack',
    scanId: 'SAI-OPS-19',
    objective:
      'Operate across a 9-component enterprise Identity and Access Management (IAM) platform — spanning Ruby authentication APIs, React admin portals, Node.js middleware, and a C# .NET Identity Provider core. Deliver features and hardening across authentication, authorization, and federation services with zero tolerance for security regression: adaptive risk policies, multi-factor authentication across seven methods, and federated SSO over SAML, OAuth 2.0, OpenID Connect, CAS, and Kerberos.',
    tactics: [
      'Extended the Ruby/Sinatra+Grape authentication service (rupert) and Admin REST API (twilight) — implementing MFA policy endpoints, HMAC-SHA256 request signing with replay-attack prevention via timestamp validation and memory cache, and Argon2 password hashing.',
      'Maintained adaptive risk-based authentication logic — BehavioSec behavioral biometrics, device fingerprinting, geographic/IP policy enforcement, and threat detection integrations with Exabeam and Cisco pxGrid for configurable conditional auth policies.',
      'Contributed to three React admin portals (spike, coruscant, dagobah) and Node.js middleware (bespin) — delivering realm, application, and data store management surfaces for enterprise administrators with full RBAC and audit logging.',
      'Maintained federated SSO flows across SAML 1.1/2.0, OAuth 2.0, OpenID Connect, CAS, and Kerberos/SPNEGO; secured credentials at rest via CyberArk Vault integration, encrypted fields, and RS256/HS256-signed JWTs with rate limiting and account lockout enforced at the request layer.',
      'Authored Swagger/OpenAPI 3.0 and Protobuf messaging contracts across all nine services; maintained multi-stack CI/CD via Jenkins + Artifactory with Jest/Enzyme, RSpec + Rubocop, and NUnit test coverage across Ruby, React, and C# components.',
    ],
    outcome: 'ZERO-TRUST AUTH DELIVERED',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'right',
    imageUrl: 'images/sat.avif',
  },
  {
    date: '2017.Q1 — 2018.Q1',
    title: 'Operation: Energy_Cloud',
    role: 'Software Engineer, Full-Stack',
    scanId: 'EC-OPS-17',
    objective:
      'Engineer a B2B SaaS platform automating the complete commercial LED lighting retrofit lifecycle — from field audit through algorithm-driven fixture replacement matching, financial analysis, and multi-supplier purchase order generation. Replace manual auditor workflows with a command-pattern engine, PDF reporting pipeline, and subscription-gated role system serving auditors, suppliers, and enterprise customers.',
    tactics: [
      'Built the core audit hierarchy (Audits → Areas → Legacy Fixtures) with photo annotation support; engineered a replacement matching algorithm across 17 Mutations gem command classes — automatically pairing legacy fixtures to compatible LED products based on lamp shape, base size, voltage, lumen output, and kelvin temperature.',
      'Developed a financial analysis engine calculating energy savings, ROI, payback period, and financing options per audit — generating professional PDF quotes and signed audit reports via WickedPDF + wkhtmltopdf for customer-facing deliverables.',
      'Built a multi-supplier product catalog with bulk Excel/CSV import via Roo gem and real-time import progress feedback via ActionCable WebSockets; managed async Sidekiq jobs for long-running product imports and image processing against PostgreSQL and Paperclip file storage.',
      'Integrated Zoho Subscriptions webhook pipeline for automated subscription lifecycle management — activations, upgrades, and cancellations automatically toggling user roles and permissions via CanCanCan + RoleModel RBAC across the Auditors, Suppliers, Admins, and Invitors role hierarchy.',
      'Delivered multi-supplier purchase order generation with EasyPost shipping address validation; maintained an ActiveAdmin panel for platform management; deployed via Capistrano + Passenger on DigitalOcean with Honeybadger error tracking across a 113-migration PostgreSQL schema.',
    ],
    outcome: 'AUDIT-TO-ORDER LIVE',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'left',
    imageUrl: 'images/nrg.avif',
  },
  {
    date: '2017.Q3 — 2018.Q2',
    title: 'Operation: 5NGo',
    role: 'Software Engineer, Back-End',
    scanId: 'FNG-OPS-17',
    objective:
      'Architect and deliver the JSON API backend for a location-based social gaming platform — pairing strangers in real-world PostGIS game zones to physically meet, scan QR codes, and collaboratively produce geotagged narrative content. Design a Redis-backed matchmaking engine, a six-stage game state machine, and real-time WebSocket delivery for iOS and Android clients — with zero tolerance for stale game state or mismatched pairs.',
    tactics: [
      'Built the game state machine (assigned → started → confirmed → created → finished/failed) with PostGIS-backed geographic zone management — enforcing time-window activation, meetup point assignment, QR code confirmation for physical presence validation, and story/scenario prompt sequencing per zone.',
      'Engineered a Redis-backed real-time matchmaking engine — queuing players per game zone and pairing by experience category (newby/experience/sponsored) with blocked/reported user exclusion; delivered live game state updates via ActionCable WebSockets (NotificationChannel, CommonChannel).',
      'Implemented DCI (Data, Context, Interaction) architecture via the dci gem — organizing matchmaking, creation upload, and zone lifecycle logic into dedicated app/context/create_mode/ contexts; wired rpush (APNS/FCM) push notification pipelines for all game flow events.',
      'Delivered a versioned JSON API (versionist, Accept header routing) across create_mode, explore_mode, users, game_zones, likes, reports, and blocks namespaces — with Devise + custom token auth, Facebook Account Kit social login, and Swagger documentation across all endpoints.',
      'Deployed Sidekiq workers across five dedicated queues (default, mailers, create_mode, game_zone, online_statistics) with Clockwork scheduled tasks; managed CarrierWave + fog-aws S3 uploads for geotagged creations; maintained ActiveAdmin + CanCanCan panel for zone, story, and user moderation.',
    ],
    outcome: 'GEOSPATIAL GAME LIVE',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'right',
    imageUrl: 'images/5nG.avif',
  },
  {
    date: '2016.Q4 — 2017.Q3',
    title: 'Operation: Half Cost Hotels',
    role: 'Software Engineer, Back-End',
    scanId: 'HCH-OPS-16',
    objective:
      'Architect and deliver a production-grade REST API backend for a last-minute hotel discount platform — connecting hotel managers and guests through dual-gateway financial operations, database-level dynamic pricing, and automated ACH payout pipelines. Implement three concurrent state machines across bookings, subscriptions, and payouts; encapsulate all business logic across ~111 DCI context classes; serve a dual-namespace versioned API for managers and customers on mobile and web.',
    tactics: [
      'Designed a DCI architecture with ~111 single-use Context objects (.perform()) under app/context/ — encapsulating booking holds, payment flows, payout initiation, and subscription billing per use case with fully thin controllers.',
      'Implemented three concurrent AASM state machines — Booking (on_hold → waiting_for_payment → upcoming → current → past), Subscription (pending → active → past_due → canceled), and Payout (created → processing → done/failed) — with 15-minute hold expiration enforced via Sidekiq-Cron.',
      'Built dual-gateway payment infrastructure: Braintree for customer subscription billing and saved card management; Dwolla for automated ACH hotel earnings payouts — with hourly Sidekiq-Cron jobs driving payout initiation and subscription state reconciliation.',
      'Implemented custom PostgreSQL pricing functions (hotel_discount(), discounted_price()) for dynamic first-night and per-night discount computation; delivered a complex hotel search engine (price range, dates, rating, amenities, beds, parking, dining) with cursor-based pagination.',
      'Delivered a dual-namespace versioned JSON API (/api/v1/managers, /api/v1/customers) with custom TokenAuth + Facebook/Google OAuth social login; wired Firebase Cloud Messaging push, ActionCable WebSocket, and SMTP notifications via a polymorphic Notification model; deployed via Dokku + Puma.',
    ],
    outcome: 'DUAL-GATEWAY LIVE',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'left',
    imageUrl: 'images/htl.avif',
  },
  {
    date: '2015.Q4 — 2016.Q3',
    title: 'Operation: Inviteez', // TODO: hide project name
    role: 'Software Engineer, Back-End',
    scanId: 'INV-OPS-15',
    objective:
      'Architect and deliver a REST API backend for a mobile event invitation platform — enabling users to create events, invite contacts via phone, email, or platform account, manage RSVPs, and engage in real-time event chat with push notification delivery across 15+ notification types. Build shadow account infrastructure for non-registered invitees, phone-first SMS authentication, and STI-based notification dispatch for iOS-first mobile clients.',
    tactics: [
      'Built a full event management and smart invitation API — supporting registered users, phone/email contacts, and token-based invite links; implemented shadow accounts for non-registered invitees and RSVP status tracking (accepted/declined/no reply) across the invitation lifecycle.',
      'Architected phone-first authentication via Nexmo SMS verification + Doorkeeper OAuth 2.0 password grant with token/refresh flow; enforced Pundit policy-based authorization across all event, invitation, chat, and album resources.',
      'Delivered an event chat system with JSON-structured messages, embedded photo support, and per-user read state; built per-event photo albums with MD5 duplicate detection and CarrierWave + MiniMagick image processing via Sidekiq background workers.',
      'Implemented an STI-based Notification model consolidating 15+ notification types in a single table — backed by Rpush APNS push delivery for iOS; wired Sidekiq + Whenever cron for scheduled RSVP reminder dispatch across active events.',
      'Shipped a versioned JSON-API (V1 full, V2 limited) via Versionist + ActiveModel Serializers with soft-delete archiving (deleted_at) across all records; instrumented with Rollbar error tracking, New Relic APM, and Mandrill transactional email via MarkerB.',
    ],
    outcome: '15+ PUSH TYPES LIVE',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'right',
    imageUrl: 'images/evnt.avif',
  },
  {
    date: '2016.Q3 — 2017.Q2',
    title: 'Operation: The Walk',
    role: 'Software Engineer, Back-End',
    scanId: 'TW-OPS-16',
    objective:
      'Architect and deliver a JSON API backend for a mobile and web spiritual content platform — serving personalized teachings, guided prayers, and multi-translation Scripture passages to global audiences. Integrate Contentful CMS for bulk content import, build a four-job async media processing pipeline via FFmpeg and AWS Elastic Transcoder, and model polymorphic engagement (favorites, follows, notes, views) consistently across all six content types.',
    tactics: [
      'Designed a versioned Rails 5 JSON API across 21 service classes, 20 serializers, and 19 controllers — with polymorphic Favorites, Follows, Notes, and Views spanning Teachings, Prayers, Bible Passages, Topics, Authors, and Organizations via concern-based Searchable, Viewable, and AttachmentOptimizable mixins.',
      'Integrated Contentful CMS for bulk content import — syncing video/audio Teachings (with clip segments), multi-step guided Prayers, and multi-translation Bible Passages (NIV/ESV/NLT) into PostgreSQL via Sidekiq background workers.',
      'Built a four-job async media processing pipeline: FFmpeg server-side transcoding, AWS Elastic Transcoder format conversion, and Tinify image compression — serving processed assets via AWS S3 + CloudFront CDN with scope-aware ActiveModelSerializers JSON delivery.',
      'Implemented Challah gem authentication with guest user support and four OAuth providers (Facebook, Google, Instagram, Twitter); delivered personalized topic-interest content feeds, per-user Bible translation preferences, and full-text PostgreSQL search.',
      'Documented all endpoints with Swagger; maintained 40+ API integration test specs via RSpec + FactoryBot + VCR across 92+ PostgreSQL migrations; managed content and platform data through an ActiveAdmin (ArcticAdmin theme) panel backed by Sidekiq + Redis.',
    ],
    outcome: 'MULTI-TYPE CONTENT LIVE',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'left',
    imageUrl: 'images/twlk.avif',
  },
  {
    date: '2016.Q1 — 2016.Q4',
    title: 'Operation: Staffing',
    role: 'Software Engineer, Back-End',
    scanId: 'SP-OPS-16',
    objective:
      'Architect and deliver a recruitment SaaS platform API — connecting job seekers and employers through dual-sided application state machines, intelligent vacancy matching, and a full hiring pipeline. Build STI-based user hierarchy, company verification workflows, video introduction uploads, and DCI-pattern business logic across 38+ context classes, serving stateless mobile and web clients through a versioned JSON API.',
    tactics: [
      'Designed DCI architecture with 38+ context classes under app/context/ — controllers delegate all business logic (profile management, application transitions, company verification, vacancy matching) to dedicated context objects, keeping the codebase isolated and testable across 99 RSpec spec files.',
      'Engineered STI-based user hierarchy (User → Candidate/Manager) with dual state machines tracking both sides of each application simultaneously — candidate-side (matching → applied → declined) and manager-side (pending → shortlisted → rejected) — and a polymorphic feed model serving personalized vacancy + post streams.',
      'Built candidate profile system covering work history, education, trainings, languages, photos, and video introductions — processing video via FFmpeg, storing assets via CarrierWave + AWS S3, and enabling employer job-history verification workflows.',
      'Integrated Stripe payment pipeline for premium features; delivered four notification channels — in-app, Rpush iOS/Android push, Mandrill transactional email, and YoChat in-app messaging — across application pipeline, social, and company events.',
      'Shipped a versioned JSON API (/api/v1/ via Accept header) with stateless bearer token auth (2-day expiry), CanCan authorization, Facebook/Instagram/Twitter OAuth login, and SwaggerEngine OpenAPI 2.0 docs; deployed via Capistrano 3 + Puma + Nginx with GitLab CI/CD and Docker-based test runs across 146 PostgreSQL migrations.',
    ],
    outcome: 'DUAL-SIDED PIPELINE',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'right',
    imageUrl: 'images/stf.avif',
  },
  {
    date: '2015.Q3 — 2016.Q2',
    title: 'Operation: VoVi',
    role: 'Software Engineer, Back-End',
    scanId: 'VV-OPS-15',
    objective:
      'Architect and deliver a Rails 5 API backend and admin CMS for an educational video content delivery platform — distributing lessons across four media formats (video, audio, text, image) to iOS and Android mobile clients. Implement DCI-pattern domain logic for lesson discovery and filtering, Rpush push notification delivery, and an ActiveAdmin editorial panel — serving a category-organized content library to a global mobile audience.',
    tactics: [
      'Designed DCI context classes (FindLessons, SearchLessonsByTitle, GetFilteredLessons) encapsulating all domain logic for lesson discovery, full-text title search, quality/year filtering, and featured lesson recommendations — with AMS serializers in the api/v1/ namespace across paginated, category-filtered, and ID-list endpoints.',
      'Built a multi-format lesson content model with nested YouTube video URLs, S3-hosted MP3 audio (CarrierWave + fog-aws), uploaded text documents, and images — with metadata tracking (location, quality, date), category-based organization, and view count increment via PATCH /api/lessons/:id.',
      'Wired Rpush APNS + GCM/FCM push notification pipeline with Sidekiq background workers — handling iOS/Android device registration (POST /api/devices) and async notification delivery alongside YouTube video duration fetching and audio metadata extraction jobs.',
      'Integrated Stripe payment pipeline for subscription features; implemented Facebook/Instagram/Twitter/Google/YouTube OAuth social integrations via Koala for user authentication and content discovery across the platform.',
      'Deployed across three environments (production/staging/dev) via Capistrano 3 + Puma + Nginx with shared .env secrets, preserved upload/log directories across releases, daily CarrierWave cache cleanup cron, and GitLab CI; managed all content via ActiveAdmin with full CRUD, batch operations, and media upload support.',
    ],
    outcome: '4-FORMAT LESSON API',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'left',
    imageUrl: 'images/vv.avif',
  },
  {
    date: '2015.Q1 — 2015.Q4',
    title: 'Operation: Yalta',
    role: 'Software Engineer, Full-Stack',
    scanId: 'YW-OPS-15',
    objective:
      'Engineer and maintain a corporate marketing website and publishing platform for a mobile development company — designed to showcase portfolio case studies, publish technical blog content, and convert visitors into qualified business leads. Architect a dual-purpose Rails 4.2 monolith with YAML-based static portfolio content, block-based article composition, Pipedrive CRM lead integration, and a multi-role admin publishing workflow serving publisher, admin, and superadmin operators.',
    tactics: [
      'Built a block-based article publishing system with draft/published state management, STI-based block types (Blocks::CallToAction, Blocks::ArticleBlock via the actable gem), a five-reaction reader engagement system (Wow/Mmm/Hmm/Meh/Pff), per-article view tracking by IP + user agent, and RSS feed generation.',
      'Implemented YAML-based static content models for portfolio case studies (/data/works/) and technology showcases (/data/technologies/) — enabling content updates without database migrations while maintaining flexible layout, industry segment categorization, and tagging.',
      'Integrated Pipedrive CRM lead pipeline via contact/estimation forms with file upload, budget selection, NDA agreement, and honeypot spam protection — with CSV export and ActionMailer email notifications converting site visitors into managed sales opportunities.',
      'Built multi-session referrer trail tracking for user journey analytics; integrated Mailchimp API for category-based newsletter subscriptions; wired Google Analytics, Mixpanel, Hotjar, and Twitter API for social share count aggregation and behavioral insight.',
      'Applied Draper decorator pattern to separate view presentation from ActiveRecord models; managed Redis caching (5-min TTL) + Rack HTTP-level caching; shipped Sidekiq workers for report generation and mailers with Whenever daily sitemap cron; deployed via Capistrano 3 + RVM with CanCanCan RBAC across the ActiveAdmin panel.',
    ],
    outcome: 'LEAD-TO-CRM PIPELINE',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'right',
  },
  {
    date: '2015.Q2 — 2016.Q2',
    title: 'Operation: LoopMe',
    role: 'Software Engineer, Full-Stack',
    scanId: 'LM-OPS-15',
    objective:
      'Engineer features and analytics infrastructure on an enterprise-grade digital advertising management platform — serving advertisers, publishers, affiliates, and operations teams through the full campaign lifecycle. Navigate a large-scale Rails 5 monolith backed by Apache Kafka event streaming, AWS Redshift analytics warehousing, and Sidekiq Enterprise reliable scheduler — across 12 RBAC roles, 40+ ad formats, and 18 ad network integrations spanning five production environments.',
    tactics: [
      'Extended campaign and line item management across 40+ ad formats (banners, fullscreen, MPU, VAST/VPAID video) — implementing budget controls, frequency capping, A/B testing with control groups, geo/device/carrier/app-category targeting, and creative CRUD for image, HTML, video, and affiliate ad unit types stored via CarrierWave + S3 + CloudFront CDN.',
      'Maintained 18 ad network API integrations (MoPub, Fyber, and 16 others) and a public REST API (/api/v1/) for external partner access to campaigns, line items, creatives, and reports; supported four pricing models (CPC, CPI, CPM, CPCV) across advertiser and affiliate billing flows.',
      'Built multi-dimensional reporting dashboards — real-time KPI views (7-day and 2-day aggregations), Elasticsearch-backed large-scale queries, and Highcharts visualizations — with CSV export and scheduled email report delivery; backed by 29 statistics models and Redis caching with Sidekiq cache recalculation workers.',
      'Operated invoicing, billing log, balance tracking, and monthly reconciliation workflows across event-level cost pipelines driven by Apache Kafka streaming; managed affiliate earnings accounting alongside advertiser CPC/CPI/CPM spend — with Redshift as the analytics data warehouse.',
      'Enforced acl9 RBAC across 12 user roles (advertiser, publisher, manager, superadmin, sale, adop, affiliate, and more) with admin account impersonation; applied Draper decorator pattern for view logic separation; maintained Datadog StatsD, New Relic, and Sentry observability across Docker + Puma + Consul (service discovery) in five environments.',
    ],
    outcome: 'KAFKA-POWERED RTB',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'left',
    imageUrl: 'images/lpm.webp',
  },
  {
    date: '2014.Q3 — 2015.Q2',
    title: 'Operation: Gambitious',
    role: 'Software Engineer, Full-Stack',
    scanId: 'GMB-OPS-14',
    objective:
      'Contribute to a multi-tier equity and pledge-based crowdfunding platform targeting the European market — enabling entrepreneurs to raise capital through equity shares, reward pledges, hybrid campaigns, and charity fundraising. Navigate a mature Rails 3.2 monolith (52 models, 35 controllers, 26 service objects) with AASM project state machines, KYC identity verification, SOAP payment processing, e-signature legal agreements, and EU VAT compliance across English and Dutch markets.',
    tactics: [
      'Extended AASM-managed Idea state machines (created → pending_review → active → fully_funded/missed_deadline) across four STI subtypes (equity, pledge, hybrid, charity) — with 26 service objects handling payment orchestration, notifications, user onboarding, and Delayed Job + Whenever reminder workflows.',
      'Integrated the FEET SOAP payment gateway (custom lib/feet.rb, ~11K LOC) via Savon + IBAN-Tools for primary EUR payment processing; maintained PayPal legacy support; implemented Money-Rails EUR denomination with tiered transaction fees (2.5% standard / 1% large investors) and EU 21% VAT compliance.',
      'Wired RightSignature for legally binding e-signatures on equity investment agreements; integrated Prooflink for KYC/identity verification of equity investors; generated PDF invoices via Princely; managed file and image storage via CarrierWave + MiniMagick + AWS S3 (Fog).',
      'Maintained a full-stack HAML view layer with Draper decorators and form objects for complex investor input flows; implemented Observer-pattern NotificationObserver triggering 9 mailers on model state changes — with English/Dutch I18n across Amsterdam timezone configuration.',
      'Integrated Campaign Monitor for email marketing and investor newsletters; deployed via Capistrano 3 + RVM + Unicorn; maintained Airbrake error tracking; covered the codebase with Test::Unit + RSpec across a MySQL-backed schema serving the European equity crowdfunding regulatory environment.',
    ],
    outcome: '4-MODE CROWDFUNDING',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'right',
    imageUrl: 'images/gmb.avif',
  },
  {
    date: '2014.Q2 — 2014.Q4',
    title: 'Operation: NenCrowd',
    role: 'Software Engineer, Full-Stack',
    scanId: 'NEN-OPS-14',
    objective:
      'Deliver a crowdfunding and investment management platform — supporting multilingual project listings, a four-step investment wizard with session-based form state, and iDEAL payment processing via a custom Buckaroo gateway integration. Serve both individual and corporate investor flows with conditional Reform validation, bilingual NL/EN routing, and BettyBlocks transactional email triggers across 14 domain models.',
    tactics: [
      'Built a four-step investment wizard (reward selection → personal data → payment → confirmation) using Reform form objects with conditional validation for individual vs. corporate investors — managing session-based wizard state and handling JSONP embeddable widget endpoints for project info on external sites.',
      'Integrated the Buckaroo payment gateway via a custom lib/buckaroo/ library — supporting iDEAL Dutch banking, credit card, and invoice payment methods with signature-based webhook callback validation for tamper-proof payment confirmation.',
      'Delivered AJAX-based infinite scroll for project comments and updates; built per-project and site-wide newsletter subscription management; integrated BettyBlocks external API to trigger transactional emails on investment creation, comment activity, and project update publication.',
      'Implemented Traco column-per-locale model-level i18n and Route Translator for bilingual URL routing (/nl/, /en/); applied Draper decorator pattern for clean view logic separation across Slim + SASS + CoffeeScript frontend templates with Turbolinks navigation.',
      'Encapsulated all business logic in dedicated service objects (InvestmentCreator, TransactionProcessor, UserCreator, BettyActionEffectuator); deployed via Capistrano across a Rails 4.1 + MySQL stack targeting Amsterdam timezone and Dutch regulatory requirements.',
    ],
    outcome: 'iDEAL-POWERED CROWD',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'left',
    imageUrl: 'images/nen.avif',
  },
  {
    date: '2013.Q3 — 2014.Q3',
    title: 'Operation: NowShop',
    role: 'Software Engineer, Full-Stack',
    scanId: 'NOW-OPS-13',
    objective:
      'Contribute to a multi-tenant B2B2C e-commerce marketplace targeting Scandinavian retail — hosting independent carrier storefronts on isolated subdomains, aggregating products from multiple retailers, and routing commission-based revenue flows. Navigate a complex Rails 4 architecture (58+ models, 11 query objects) with FTP-based bulk product imports, automatic cart order splitting per retailer, GeoIP localization, and a full PayPal integration stack serving carriers like smartguy.dk, boozt.com, and coolshop.com.',
    tactics: [
      'Extended subdomain-based multi-tenancy via CarrierDetector middleware — routing carrier shop contexts through namespaced controllers (Admin/Carrier/Retailer/Public/API); maintained 58+ models and 11 query objects across a product master/variant hierarchy with SKU deduplication and FTP bulk import feed processing.',
      'Built automatic cart order splitting by retailer — decomposing mixed-cart purchases into separate payment flows per vendor — with custom order state machines (pending → processing → shipped → completed) and a per-retailer/per-category commission calculation and reporting engine.',
      'Integrated PayPal Express Checkout, IPN notifications, Adaptive Accounts, and billing agreements via a dedicated Payment::PayPal service layer; maintained Pensio gateway support; built a REST Order webhook API (v1) for retailer integrations with tokenizable record access.',
      'Delivered GeoIP detection for geographic localization, multi-currency support, and country-specific shipping logic; managed AlchemyCMS 3.0 for carrier page building and media management; scheduled product feed processing, commission calculations, and exchange rate updates via Whenever cron.',
      'Built a Backbone.js + jQuery + CoffeeScript frontend on Bootstrap SASS; maintained NewRelic APM and Airbrake error tracking; covered the platform with RSpec + Capybara + Factory Girl across a PostgreSQL schema with hstore and enforced foreign keys.',
    ],
    outcome: 'CART-SPLIT MARKETPLACE',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'right',
    imageUrl: 'images/nw.avif',
  },
  {
    date: '2014.Q4 — 2015.Q4',
    title: 'Operation: Revolution',
    role: 'Software Engineer, Full-Stack',
    scanId: 'R9-OPS-14',
    objective:
      'Build and extend a multi-tenant SaaS CMS platform enabling musicians and artists to launch and manage professional websites without writing code — deployed under revolve-music.com. Architect three cooperating sub-applications: a public marketing site, a 27-controller admin panel for content and subscription management, and a Liquid-powered CMS renderer mapping vanity subdomains and custom domains to artist sites. Operate across content publishing, subscription billing, fan engagement, and white-label design tooling.',
    tactics: [
      'Engineered multi-domain routing via a Custom Domain constraint class — resolving incoming requests to the correct artist CMS context by subdomain or custom domain; maintained 48 ActiveRecord models across content domains (albums, tracks, tour dates, photo albums, blog posts, news, video pages) with CarrierWave + MiniMagick + Fog cloud media storage.',
      'Built a Liquid template rendering pipeline for artist public sites — exposing layout, page, menu, resource, and partial template editors alongside a custom CSS/JS editor, Adobe Typekit font integration, and a visual design mode for hero imagery and color themes; backed by a service layer under app/services/ for CMS rendering and design mode logic.',
      'Integrated Adyen recurring payment processing — handling tiered subscription plans with visitor/feature limits, trial periods, upgrade/downgrade flows, and billing agreement management; automated subscription expiration checks and payment status reconciliation via Delayed Job workers and Whenever cron scheduling.',
      'Delivered fan engagement infrastructure: Campaign Monitor (CreateSend) integration for email capture and list management, a comment system across blog/news/video content types, visitor tracking, and social media profile link management (Spotify, iTunes, YouTube, and more).',
      'Maintained a HAML/Slim admin view layer across 27 controllers with Devise authentication; applied Dalli (Memcached) caching for CMS rendering throughput; covered the platform with RSpec + Factory Girl + Capybara; deployed via Capistrano 3 + Monit on a MySQL-backed Rails 4.0 + Ruby 2.1.5 stack.',
    ],
    outcome: 'ARTIST CMS PLATFORM',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'left',
    imageUrl: 'images/rv.avif',
  },
  {
    date: '2013.Q2 — 2013.Q4',
    title: 'Operation: Discount',
    role: 'Software Engineer, Full-Stack',
    scanId: 'D4Y-OPS-13',
    objective:
      'Deliver a Rails 3.2 e-commerce catalog for a furniture and home goods retailer — enabling customers to browse discounted beds, sofas, and related products by category, view detailed specs, and proceed through a shopping flow. Build across 9 domain models with Devise-managed authentication, dual admin interfaces, AJAX-based cart mechanics, and a Capistrano-deployed production stack targeting MySQL on a live VPS.',
    tactics: [
      'Modelled 9 core domain entities (Product, Category, User, Comment, Country, Factory, Type, Model, Metum) capturing furniture-specific attributes — sleep places, clothes box, mechanisms, dimensions, materials — with Paperclip image attachments and Kaminari/will_paginate pagination (6 products per page in production.',
      'Implemented a category-browsable product catalog with detail pages, similar product recommendations, and a CommonDefines shared module for consistent page parameter validation across controllers; integrated GMaps4Rails (Google Maps) for location-aware pages.',
      'Built AJAX-based shopping cart foundations (BasketController, AjaxController) with Devise user authentication — registration, login, and password recovery flows — and static informational pages (how to buy, warranty, shipping, about, contacts).',
      'Mounted dual admin interfaces (RailsAdmin + ActiveAdmin) at /admin for content and product data management; deployed via Capistrano + RVM remote-cache strategy with symlinked database.yml, uploads/, and system/ directories on a MySQL-backed production VPS.',
    ],
    outcome: 'FURNITURE CATALOG',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'right',
    imageUrl: 'images/d4u.avif',
  },
  {
    date: '2014.Q3 — 2016.Q1',
    title: 'Operation: Kyiv.Guide',
    role: 'Software Engineer, Full-Stack',
    scanId: 'KGA-OPS-14',
    objective:
      'Build and extend a production-grade multilingual city guide platform for Kyiv — aggregating tourism attractions, dining, accommodation, events, and transit across four language markets (EN, UK, RU, DE). Architect a BrowserCMS-backed editorial layer on Rails 3.2, wire a live Feratel XML data sync pipeline for hotel inventory, and deliver full-text search, geolocation maps, and scheduled background workers across a long-running MySQL production deployment.',
    tactics: [
      'Implemented Globalize3 DB-backed translations across all content models (tourism places, food venues, events, carriers, news, accommodation) — serving four locales (English, Ukrainian, Russian, German) from a single schema with locale-aware routing and editorial workflows.',
      'Built a Feratel accommodation sync pipeline using LibXML-Ruby to parse XML feeds from interface.deskline.net — UpdateAccommodationDataWorker and GetKeyValuesWorker scheduled via Sidekiq 2 + sidekiq-cron to keep hotel/hostel data (star ratings, facilities, classifications) continuously reconciled against the upstream API.',
      'Delivered geolocation-enabled content across tourism places, food venues, events, and carriers — storing GPS coordinates per entity and rendering interactive Google Maps via gmaps4rails; managed Paperclip + FFmpeg media pipelines for image and video asset handling.',
      'Integrated Thinking Sphinx 3 full-text search across all content types; built BrowserCMS portlet system for modular editorial blocks (carousels, banners, booking widgets, social tabs); implemented fragment caching with a dedicated CacheResetController and Sweepers to manage cache invalidation on editorial updates.',
      'Maintained 100+ DB migrations tracking schema evolution from initial July 2014 commit; managed editorial content via the BrowserCMS admin interface; deployed via Capistrano 2 + RVM on a MySQL-backed Rails 3.2.14 stack in a stable, long-running production configuration.',
    ],
    outcome: '4-LOCALE CITY GUIDE',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'left',
    imageUrl: 'images/ky.avif',
  },
  {
    date: '2014.Q2 — 2015.Q1',
    title: 'Operation: NOW',
    role: 'Software Engineer, Full-Stack',
    scanId: 'NWB-OPS-14',
    objective:
      'Architect and deliver the backend platform for a location-based events and places discovery app targeting mobile users across Russian-speaking cities — exposing a REST API for iOS and Android clients alongside a multilingual web catalog and a four-tier admin panel. Operate on a MongoDB/Mongoid stack with 2D geospatial indexing, Redis-cached translations, and device token authentication — surfacing nearby events, venue discovery, and automatic city detection from user coordinates.',
    tactics: [
      'Modelled core domain in MongoDB/Mongoid ODM — Event (news, concerts, discounts, other), Place (restaurants, theaters, stores), City, Category, SubCategory, PlaceCategory, Banner, and Translation — with MongoDB 2D geospatial indexes on all location-aware documents for radius-based city auto-detection and proximity filtering.',
      'Built a mobile REST API (/api/customer/*) with device token authentication via Devise for iOS and Android clients — covering registration, login, city detection from coordinates, event/place listings, category filters, and user settings; serialized all responses via acts_as_api profile definitions with per-format field control.',
      'Implemented a multilingual content layer (Russian, English, Yakut) using Mongoid localize: true for field-level document translations — backed by MongoDB-stored Translation documents and a Redis cache with 3-min TTL for high-frequency locale lookups across all content types.',
      'Enforced CanCan role hierarchy (super admin → city admin → controller → manager) with city-scoped ability definitions for multi-tenant admin access; mounted ActiveAdmin for full CRUD across all entities; managed Paperclip + ImageMagick image pipelines with five style variants (gallery, medium, thumb, small, logo).',
      'Delivered a multilingual web front-end (/:locale/* routing) for event and place catalogs, full-text search, contacts, and partner pages — backed by Redis session caching and a stable Rails 3.2.16 + MongoDB production stack.',
    ],
    outcome: 'GEO-AWARE MOBILE API',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'right',
    imageUrl: 'images/nwb.avif',
  },
  {
    date: '2013.Q1 — 2013.Q4',
    title: 'Operation: Scrij',
    role: 'Software Engineer, Full-Stack',
    scanId: 'SCR-OPS-13',
    objective:
      'Build a geospatially-aware, media-rich task management platform for cross-device synchronization across iOS, Android, and web — enabling users to create todos annotated with GPS-located SuperTags, attach photo/video/audio resources, collaborate within role-based organizations, and receive push notifications. Architect a dual-namespace Rails 3.2 stack: a token-authenticated mobile REST API and a browser-based web interface with maps, calendar, and dashboard views.',
    tactics: [
      'Modelled a rich domain hierarchy — User → Organization + Role → Todo (priority, dates, status, type) → SuperTag (lat/long/altitude) → BaseResource STI (photo/video/audio) → Comment — with HABTM todo sharing across team members and Contact linkage (emails, phones); tracked registered mobile clients via Scrijdevices (push token, UDID per user).',
      'Engineered a two-way sync engine detecting adds, updates, and deletes across iOS, Android, and web clients — reconciling delta state per device session to keep all platforms consistent without full payload re-fetches; implemented /api namespace with Devise token authentication and acts_as_api response profiles for all mobile endpoints.',
      'Integrated APNS push notifications via Grocer for iOS and GCM for Android — triggering alerts on todo assignment, status changes, and team activity from server-side events; managed Scrijdevices token lifecycle for reliable delivery across client re-registrations.',
      'Built Paperclip + paperclip-ffmpeg media pipeline with Fog cloud storage for multi-format resource attachments (photo gallery, video transcoding, audio clips) across SuperTag annotations; rendered geo-located SuperTags on interactive Google Maps via gmaps4rails in the /web interface with calendar and dashboard views.',
      'Enforced CanCan organization-scoped authorization (admin / manager / user roles) with Devise session auth for the web layer; delivered ActiveAdmin panel with Globalize3 multilingual support (EN/RU); deployed via Capistrano + RVM on a MySQL-backed production stack.',
    ],
    outcome: 'MULTI-DEVICE TASK SYNC',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'left',
    imageUrl: 'images/sk.avif',
  },
  {
    date: '2015.Q3 — 2016.Q3',
    title: 'Operation: Safety Sophite',
    role: 'Software Engineer, Full-Stack',
    scanId: 'SFTY-OPS-15',
    objective:
      'Build a white-label home security and real-time safety coordination platform for IoT — serving mobile clients (iOS/Android) and a web dashboard across 52 models, 40+ REST endpoints, and 13 async Sidekiq workers. Architect alarm management with live location broadcasting, a hierarchical trustee/guardian permission system, IoT device telemetry, multi-unit building management, and a multi-channel notification layer (push, SMS, email, Facebook) on a MySQL + Redis + Faye WebSocket stack deployed to AWS Elastic Beanstalk.',
    tactics: [
      'Modelled 52 ActiveRecord entities across safety domains — Alarm (send/cancel with shared location links), FollowMe (live location sharing sessions), Trustee (hierarchical guardian relationships with NONE/VIEWER/MANAGER/MASTER permission tiers), IMP IoT devices (battery, signal, temperature, humidity telemetry), MDU multi-unit buildings (floors, apartments, common areas, fire communities), and Organization for white-label tenant isolation.',
      'Delivered a 40+ endpoint REST API across 16 controllers — all POST-based with auth_token header authentication — organized into functional groups (auth, user, home, imp, trustee, alarm, follow_me, mdu, notification, system); token strategy layered on Devise for stateless mobile client access.',
      'Implemented real-time alarm broadcasting and live location sharing via Faye + Redis pub/sub WebSocket channels — enabling instant alarm propagation to trustees and followers without polling; managed 13 Sidekiq workers + Sidekiq-Cron for async notification dispatch, scheduled safety checks, and IoT telemetry ingestion.',
      'Built a multi-channel notification pipeline routing alerts through APNs (Grocer) for iOS, GCM for Android, SMS, Email, and Facebook — triggered by Sidekiq workers on alarm events, trustee updates, and IoT threshold breaches; maintained Paperclip + AWS S3 for user media and device asset storage.',
      'Deployed to AWS Elastic Beanstalk via Capistrano 3; maintained ActiveAdmin dashboard for operational oversight; backed by MySQL (primary data) + Redis (caching, sessions, pub/sub) across a HAML/SASS/CoffeeScript + jQuery frontend layer.',
    ],
    outcome: 'REALTIME SAFETY NETWORK',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'right',
    imageUrl: 'images/sft.avif',
  },
  {
    date: '2016.Q2 — 2017.Q1',
    title: 'Operation: Taxi',
    role: 'Software Engineer, Full-Stack',
    scanId: 'STX-OPS-16',
    objective:
      'Architect and deliver the backend platform for a Ukrainian ride-sharing service — exposing three distinct mobile API namespaces for riders, drivers, and dispatch operators across 47 Mongoid models and 13 async Sidekiq workers. Implement a full order lifecycle state machine, MongoDB geospatial driver matching, four Ukrainian payment gateway integrations with SHA1 signature verification, and a multi-channel notification layer (push, SMS, email) serving an iOS/Android mobile fleet.',
    tactics: [
      'Modelled 47 Mongoid documents covering the ride-hailing domain — Customer, Driver, Order (multi-stop destinations, hot/cold types), Car, DriverLocation, DriverTransaction, Region, Rate, Feedback, PushAlert — with an order lifecycle state machine (open → accepted → in_progress → closed/canceled) and bidirectional rating flows (customers rate drivers, drivers rate customers).',
      'Designed three dedicated API namespaces: /api/customer/ for rider order placement and tracking, /api/driver/ for order acceptance and live location updates, /api/dispatcher/ for operator-managed manual order placement and phone integration — each with scoped authentication and role-appropriate response contracts.',
      'Implemented MongoDB geospatial $near queries on DriverLocation documents for real-time proximity-based driver matching; maintained per-region pricing configuration (boarding fee + per-km rate, speed estimates, regional support contacts) to support multi-city deployment.',
      'Integrated four Ukrainian payment processors — Nonstop24, Citypay, Easysoft, Privat24 — alongside cash flow, all with SHA1 callback signature verification; built phone-based OTP auth (login11 flow) via Devise alongside Facebook and VKontakte (VK.com) social login for the Eastern European market.',
      'Operated 13 Sidekiq + Sidekiq-Cron background workers handling APNS/GCM push notifications, SMS.ru and email dispatch, fee processing, order timeout auto-cancellation, and DriverLocation document cleanup; backed by Redis for sessions and caching; managed via ActiveAdmin with Russian/Ukrainian i18n.',
    ],
    outcome: 'TRI-ROLE RIDE-HAIL API',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'left',
    imageUrl: 'images/tx.avif',
  },
  {
    date: '2013.Q4 — 2014.Q3',
    title: 'Operation: TravelPlaces',
    role: 'Software Engineer, Full-Stack',
    scanId: 'TRP-OPS-13',
    objective:
      'Build a multi-region, multi-language travel destination discovery platform for Eastern Europe and the Caucasus — serving curated place guides across regional subdomains (Crimea, Donetsk, Batumi, Lviv) to both a public web audience and iOS/Android mobile clients. Architect subdomain-based multi-tenancy, five-locale DB-level translations, a mobile JSON API with incremental version-tracked sync, and a region-scoped admin panel with SEO and sitemap coverage.',
    tactics: [
      'Implemented subdomain-based multi-tenancy routing each regional portal (crimea / donetsk / batumi / lviv) to its own scoped layout and content set — built on core models: Place, Category, Region, Image, AdminUser, Language; managed Globalize3 DB-level translations across five locales (Russian, English, Ukrainian, Georgian, Polish) with Russian as default.',
      'Delivered a dual-access layer: a public HomeController web interface (index, search, category browse, place detail with Kaminari pagination and SEO meta tags + sitemap) and a JSON REST APIController for mobile clients — serving places, categories, and map data with version tracking for incremental sync without full payload re-fetches.',
      'Stored GPS coordinates on Place records and rendered interactive location maps via gmaps4rails (Google Maps); managed Paperclip image pipelines with mobile-optimized size variants (120×120 through 640×1136) to serve appropriately sized assets to web and native app clients.',
      'Enforced region-scoped ActiveAdmin access control — restricting non-super-admins to managing only their own region\'s content — with full CRUD for all editorial entities; built full-text search across place names and descriptions across the multilingual corpus.',
      'Delivered a Bootstrap 3 + jQuery + SASS/CoffeeScript frontend with acts-as-api response serialization for mobile endpoints; deployed via Capistrano + RVM on a MySQL-backed Rails 3.2 production stack.',
    ],
    outcome: '5-LOCALE TRAVEL GUIDE',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'right',
    imageUrl: 'images/tv.avif',
  },
  {
    date: '2018.Q2 — 2019.Q4',
    title: 'Operation: Bible',
    role: 'Software Engineer, Full-Stack',
    scanId: 'WBS-OPS-18',
    objective:
      'Build and extend a large-scale, multi-language online and postal Bible education platform connecting students worldwide with volunteer teachers — managing course assignment lifecycles, student-teacher board matching, group congregation billing, and spiritual follow-up workflows. Operate across 70+ models, 37 Pundit policies, 19 Sidekiq workers, and 10 mailer modules on a Rails 5.2 DDD-influenced monolith with React 16 + Redux, JWT-auth REST API, and full four-locale i18n routing.',
    tactics: [
      'Modelled the core educational domain — Course → Exam → LessonSegment → Question → Choice — with STI (User → Student | Teacher) and Statesman state machines driving the Assignment lifecycle (pending → started → completed → graded → reviewed → Certificate generation); backed by RailsEventStore event sourcing for a full audit trail of key domain transitions.',
      'Built a Board marketplace enabling teachers to adopt unassigned students from an open queue; implemented FollowupRequest spiritual workflows (baptism coordination, church introduction); managed campaign subdomain multi-tenancy for student acquisition channels (web, postal, referral) with per-campaign routing and analytics.',
      'Delivered a REST API at /api/v1/ with JWT authentication and JSON API serializers; maintained localized routes across four languages (English, Portuguese, Spanish, French) with complete i18n coverage across all 70+ models and 10 mailer modules; enforced 37 Pundit RBAC policy files governing fine-grained access across all user roles.',
      'Integrated Stripe for group congregation billing — invoicing, subscription management, and campaign payment flows; managed AWS S3 + CarrierWave file storage for course materials and certificates; wired Intercom for student support, Slack for internal alerts, New Relic for APM, and Cloudflare for edge performance.',
      'Delivered React 16 + Redux frontend modules via Webpacker alongside a legacy jQuery/CoffeeScript layer; operated 19 Sidekiq + Redis background workers for grading queues, mailer dispatch, and expiration workflows; deployed to Heroku production with Docker Compose local dev parity.',
    ],
    outcome: 'GLOBAL EDUCATION PLATFORM',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'left',
    imageUrl: 'images/bb.avif',
  },
  {
    date: '2020.Q2 — 2022.Q4',
    title: 'Operation: Data Citadel',
    role: 'Full-Stack Engineer',
    scanId: 'DC-OPS-88',
    objective:
      'Reconstruct fragmented analytics infrastructure for a high-volume SaaS platform. Analysts across product, sales, and operations lacked reliable data pipelines to drive business decisions. Mandate: design a unified, distributed intelligence layer and expose it through clean, cross-team APIs — without disrupting live production.',
    tactics: [
      'Designed distributed event-driven pipelines feeding real-time cross-departmental dashboards, eliminating manual reporting.',
      'Delivered React-based internal tooling surfaces for order metrics, churn signals, and usage intelligence across four business units.',
      'Authored RESTful and GraphQL API contracts with clean, versioned schemas — adopted as the standard integration layer company-wide.',
    ],
    outcome: '4 UNITS UNIFIED',
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'right',
    isShield: true,
  },
  {
    date: '2017.Q1 — 2020.Q1',
    title: 'Operation: Foundation Layer',
    role: 'Software Engineer, Full Stack',
    scanId: 'FL-CORE-33',
    objective:
      'Rebuild frontend architecture for a growth-stage B2B platform whose jQuery monolith had become a hard blocker on feature velocity. Objective: migrate to a scalable, OOP-aligned component system with maintainable state management — while preserving shipping cadence.',
    tactics: [
      'Executed full migration from jQuery monolith to React, introducing Redux state management and a reusable component library.',
      'Implemented a CSS-in-JS (Emotion) design system, eliminating cross-squad style conflicts and accelerating UI delivery.',
      'Collaborated with the Rails backend team on shared API schema design, SQL/NoSQL query optimization, and integration test coverage.',
    ],
    outcome: '-70% TECH DEBT',
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'right',
    isGhost: true,
  },
];
