export interface MissionData {
  date: string;
  title: string;
  role: string;
  scanId: string;
  objective: string;
  tactics: string[];
  tools?: string[];
  outcome: string;
  status: string;
  statusColor: string;
  align: 'left' | 'right';
  isShield?: boolean;
  isGhost?: boolean;
  imageUrl?: string;
}

export const missions: MissionData[] = [
  {
    date: '2024.Q1 — 2024.Q4',
    title: 'Operation: WONDER LAKE',
    role: 'Software Engineer, Full-Stack',
    scanId: 'BWF-OPS-24',
    objective:
      'Radio warfare units in the field don\'t get a second chance — missed detections, delayed commands, and stale firmware are mission failures. Built a TypeScript monorepo IoT platform where NestJS CQRS ingests device telemetry over dual Socket.IO gateways, NATS JetStream distributes events without loss, BullMQ processes detection groups and signal tracks in the background, and a React 18 operator dashboard streams real-time updates the moment they happen — with a device emulator workspace for testing before hardware arrives.',
    tactics: [
      'A domain built for electronic warfare at scale — modelled 14 TypeORM entities (Device, Detection, DetectionGroup, SignalTrack, Suppression, Command, Firmware, FrequencyWhitelist, FrequencyTable, Tag, User, and more) across a NestJS CQRS architecture where Commands and Queries decouple module boundaries; managed with Docker Compose across PostgreSQL 16, Redis, and NATS JetStream.',
      'Two WebSocket gateways, one real-time pipeline — engineered dual Socket.IO namespaces: /devices for device-to-server telemetry ingestion and command delivery, /frontend for server-to-dashboard live streaming; backed by BullMQ queues for detection group lifecycle management and signal track processing under sustained IoT event throughput.',
      'Command, suppress, update — without leaving the dashboard — delivered full operator workflows: detection group management, auto/manual suppression events, firmware OTA distribution, frequency whitelist enforcement, and per-device settings and command dispatch, all surfaced through TanStack Query server state and Zustand client state on a React 18 + Vite frontend.',
      'Maps, charts, and real-time signal data — rendered device positions and detection zones on Leaflet maps with live Socket.IO updates; visualized telemetry trends and analytics via Recharts/D3.js; supported multi-language operator interfaces via React Intl i18n.',
      'Three roles, full test coverage, production-grade observability — enforced JWT + RBAC with Admin, Operator, and Observer permission tiers across all REST and WebSocket surfaces; shipped Jest unit tests (backend), Vitest unit tests (frontend), and Playwright E2E coverage; wired Sentry error tracking for field incident visibility.',
    ],
    outcome: 'DETECTED. SUPPRESSED. LIVE.',
    tools: ['TypeScript', 'NestJS', 'CQRS', 'Socket.IO', 'NATS JetStream', 'BullMQ', 'TypeORM', 'PostgreSQL', 'Redis', 'React 18', 'Vite', 'Leaflet', 'Recharts', 'JWT', 'Docker', 'Jest', 'Vitest', 'Playwright', 'Sentry'],
    status: 'ONGOING',
    statusColor: 'text-hazard bg-hazard/10',
    isShield: true,
    align: 'right',
  },
  {
    date: '2024.Q3 — 2025.Q1',
    title: 'Operation: Prague.Wedding',
    role: 'Software Engineer, Front-End',
    scanId: 'PW-OPS-24',
    objective:
      'A Prague wedding brand needed to reach couples across four language markets — without a CMS, a backend, or ongoing infrastructure costs. Delivered a multilingual React 19 SPA with serverless form handling, version-controlled blog content, international SEO coverage across all locales, and full GDPR compliance — live in production, zero servers required.',
    tactics: [
      'Four-language reach with zero backend — built as a React 19 + TypeScript SPA with React Router 7 and Vite 6, delivering home, blog listing, and dynamic blog post routes with a sticky collapsing header and mobile hamburger menu with body scroll lock.',
      'Content that stays consistent across every language switch — a four-locale i18n system (Ukrainian, English, Czech, Russian) version-controlled in a single translations.ts, with language persisted via localStorage and URL query param, and dynamic SEO meta/OG/hreflang tag updates on every switch.',
      'Conversions handled without a server — interactive service tier cards with tab-style navigation and scale/translate animations; a multi-state contact form (idle → submitting → success/error with 5s auto-close) powered by Web3Forms API for serverless submission.',
      'International discoverability built in — Open Graph, Twitter Card, geolocation tags with Prague coordinates, sitemap, and robots.txt targeting couples in four languages across search engines worldwide.',
      'Zero external dependencies for content — a version-controlled blog with multilingual posts and slug-based routing, GDPR cookie consent modal, and Privacy Policy overlay for EU compliance; no CMS, no database, no API.',
    ],
    outcome: '4 LOCALES. ZERO SERVERS.',
    tools: ['React 19', 'TypeScript', 'React Router 7', 'Vite 6', 'Web3Forms', 'i18n'],
    status: 'ONGOING',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'left',
    imageUrl: 'images/pwc.avif',
  },
  {
    date: '2022.Q2 — 2026.Q1',
    title: 'Operation: TW-BSCI',
    role: 'Software Engineer, Full-Stack',
    scanId: 'TW-BSCI-24',
    objective:
      'When you\'re synthesizing custom genes, oligo pools, and NGS panels, order state has to be live and accurate — always. Contributed to a mission-critical bioscience e-commerce platform sustaining real-time order tracking across 10+ specialized WebSocket channels and a multi-stage production pipeline (Draft → Quote → Checkout → Batch → Fulfillment) — across three SOX-compliant frontend surfaces, without dropping a status update.',
    tactics: [
      'Real-time order delivery at scale — extended the Rails 6.1 ecommerce-infrastructure service with business logic, MongoDB/Mongoid data models, Sidekiq job orchestration, and 10+ specialized ActionCable + Ably WebSocket channels (checkout, genes, IgG, NGS, designer) for live order status across all product lines.',
      'Production pipeline continuity 24x7 — extended Ruby on Rails API endpoints and public integrations powering a highly customized per-order production pipeline, sustaining throughput across complex scientific order types around the clock.',
      'Performance under complex load — optimized MongoDB query layers and Sidekiq job orchestration to sustain throughput under variable, high-complexity order loads across gene synthesis, IgG antibody, and NGS products.',
      'Full-stack feature delivery on three surfaces — extended order configurators for custom genes, oligo pools, and NGS enrichment panels on a React/Redux SPA (S3 + CloudFront), consuming a shared Radix UI design system for consistent cross-service component delivery.',
      'Confidence through contracts and observability — maintained cross-service integrity using Pact consumer-driven contract tests; contributed to multi-language test coverage (Minitest, Pytest, Jest) alongside OpenTelemetry tracing, NewRelic APM, and Sentry across the full service mesh.',
      'Three frontend surfaces, one design system — delivered React features across the main customer portal (ecommerce-client) and SOX-compliant checkout (ecommerce-checkout-frontend) using a shared Radix UI component library for consistent cross-service delivery.',
    ],
    outcome: 'LIVE UPDATES. SOX-READY.',
    tools: ['Rails 6.1', 'Ruby', 'MongoDB', 'Sidekiq', 'ActionCable', 'Ably', 'React', 'Redux', 'Radix UI', 'Pact', 'OpenTelemetry', 'NewRelic', 'Sentry', 'AWS'],
    status: 'COMPLETED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'right',
    imageUrl: 'images/tw-bsci-01.webp',
  },
  {
    date: '2021.Q3 — 2025.Q1',
    title: 'Operation: Seeking Alpha',
    role: 'Software Engineer, Back-End',
    scanId: 'SA-OPS-22',
    objective:
      'Millions of investors rely on seekingalpha.com to make decisions worth real money — which means zero tolerance for latency, downtime, or regression. Operated inside a 505-model, 684-controller Rails 7 monolith serving three subscriber tiers, extending API features, optimizing query strategies across a dual-database stack, and contributing to a multi-gateway subscription infrastructure — at peak traffic, without incident.',
    tactics: [
      'Mobile and web clients served from a single API — extended Rails 7 backend APIs for iOS/Android and web consumers with JWT authentication, Pundit RBAC policies for tiered subscriber access, and RPush push notification pipelines across Free, Premium, and PRO tiers.',
      'Low-latency financial data at scale — optimized multi-layer query strategies across a dual-database stack (MariaDB 10.6 + PostgreSQL 13) with Elasticsearch 8 and Sphinx search, delivering financial articles, earnings transcripts, and analyst research under peak traffic loads.',
      'High-concurrency infrastructure that holds — leveraged Redis 7 caching, Fastly CDN page caching, and Resque background job orchestration (226+ workers) to sustain throughput across stock screeners, ETF analytics, dividend tracking, and earnings calendar data.',
      'Subscription revenue across every platform — contributed to payment infrastructure integrating Stripe, Braintree, and Zuora, covering author research bundle subscriptions, iOS/Android in-app purchases, and editorial content monetization workflows.',
      'Shipped with confidence at enterprise scale — operated within GitHub Actions + Jenkins CI/CD, Brakeman security scanning, RuboCop quality enforcement, and Datadog + Rollbar + Logstash observability across AWS (S3, SNS, Athena, CloudSearch).',
    ],
    outcome: 'MILLIONS SERVED. ZERO REGRESSIONS.',
    tools: ['Rails 7', 'Ruby', 'MariaDB', 'PostgreSQL', 'Elasticsearch', 'Redis', 'Fastly', 'Resque', 'Stripe', 'Braintree', 'Zuora', 'GitHub Actions', 'Jenkins', 'Datadog', 'AWS'],
    status: 'COMPLETED',
    statusColor: 'text-hazard bg-hazard/10',
    align: 'left',
    imageUrl: 'images/seeking-alpha.avif',
  },
  {
    date: '2021.Q1 — 2022.Q3',
    title: 'Operation: Payment Modals',
    role: 'Founding Partner, Full-Stack Engineer',
    scanId: 'PM-OPS-20',
    objective:
      'Built from zero as founding technical partner: a self-serve SaaS where any business designs a fully branded Stripe payment modal and goes live on their site in under five minutes — no backend, no integration work, no developers required. Sole architect of the product, admin panel, and marketing site, with end-to-end credential encryption and GPay, Apple Pay, and PayPal support from day one.',
    tactics: [
      'Non-technical users ship in minutes — engineered an interactive modal designer with live preview, letting anyone configure branding, copy, colors, and imagery without writing a single line of code.',
      'Every payment scenario covered — built a visual Stripe checkout form builder with full support for custom images, bespoke copy, and both recurring and one-time payment modes.',
      'From signup to first payment in five minutes — delivered a zero-friction embed model where businesses inject a single generated script tag to activate a fully hosted, production-ready payment modal on any website.',
      'Enterprise-grade credential security — implemented end-to-end encryption of sensitive Stripe credentials and configuration data to meet security compliance requirements across all tenants.',
      'Full product ownership, soup to nuts — architected and shipped the complete product surface: marketing site, admin panel, and REST API — from concept to live product as founding technical partner.',
      'Maximum payment reach — integrated GPay, Apple Pay, and PayPal payment methods, enabling businesses to accept payments across all popular methods without additional technical expertise.',
    ],
    outcome: 'LIVE PAYMENTS IN 5 MINUTES.',
    tools: ['Rails', 'Ruby', 'React', 'Stripe', 'GPay', 'Apple Pay', 'PayPal', 'PostgreSQL'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'right',
    imageUrl: 'images/pm1.avif',
  },
  {
    date: '2019.Q1 — 2022.Q1',
    title: 'Operation: Skills Factory',
    role: 'Lead Solution Engineer',
    scanId: 'SK-OPS-19',
    objective:
      'Elite coaching from Phelps, Rapinoe, Sharapova, and Shaun White — delivered to youth athletes anywhere in the world through their phone. Led a remote team of four to architect the full platform from scratch: Rails REST API, admin panel, NextJS marketing site, and React customer app — shipping a multi-gateway payment pipeline that grew paid conversion by 7%.',
    tactics: [
      'Architecture that scales without complexity — designed a modular system (Rails REST API, ActiveAdmin panel, NextJS marketing site, React customer app) that cut maintenance time and cost by 27%.',
      'Sign in anywhere — built JWT-based auth with OAuth integrations for Google, Facebook, and Apple across web and mobile; integrated Brightcove for scalable video content delivery.',
      'Revenue across every device — integrated Stripe, PayPal, and native Apple/Android In-App purchase pipelines, increasing paid conversion funnel by 7%.',
      'Quality and documentation as a competitive advantage — delivered Postgres + Redis data storage architecture, 83% test coverage, and 100% Swagger API documentation across all endpoints.',
    ],
    outcome: '+7% CONVERSION. 5M$ IN REVENUE.',
    tools: ['Rails', 'Ruby', 'NextJS', 'React', 'PostgreSQL', 'Redis', 'Stripe', 'PayPal', 'Brightcove', 'JWT', 'OAuth'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'left',
    imageUrl: 'images/theskills.webp',
  },
  {
    date: '2019.Q3 — 2020.Q2',
    title: 'Operation: 123',
    role: 'Software Engineer, Full-Stack',
    scanId: 'VC-OPS-19',
    objective:
      'Swiss businesses needed memorable URLs they could buy, manage, and renew — from one-day passes to ten-year registrations — with zero redirect downtime between states. Built a hybrid Rails + Angular SPA with eight subscription tiers, a ThriveCart webhook pipeline for atomic payment transitions, and a Delayed Job expiration engine that auto-cleans stale records within a 2-minute SLA window.',
    tactics: [
      'Seamless UX across the full keyword lifecycle — architected a hybrid Rails JSON API + Angular 5 SPA where Angular handles all modal-driven flows with real-time keyword availability checking, including pending-payment collision detection.',
      'Eight tiers, one engine — built a full keyword lifecycle machine (inactive → pending → active → expired) across 1-day to 10-year subscriptions, with Delayed Job handling async expiration and auto-cleanup of stale records within 2-minute SLA windows.',
      'Payment state that never drifts — integrated ThriveCart webhook pipeline to drive atomic payment state transitions covering approval, refund, cancellation, and renewal events, via a dedicated PaymentProcessor/ThriveProcessor service layer.',
      'Security and analytics at every step — implemented Devise + Petergate RBAC for tiered user/admin access; wired Mandrill transactional email across the full subscription lifecycle; instrumented per-keyword click analytics with bot filtering.',
      'Production-hardened from day one — deployed via Capistrano + Docker to an Apache/Puma stack with SSL termination, Zurich-timezone business logic, and environment-scoped secrets for Mandrill, ThriveCart, and MySQL credentials.',
    ],
    outcome: '8 TIERS. 2-MIN EXPIRY SLA.',
    tools: ['Rails', 'Ruby', 'Angular 5', 'MySQL', 'ThriveCart', 'Delayed Job', 'Devise', 'Mandrill', 'Docker', 'Capistrano'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'right',
    imageUrl: 'images/123.avif',
  },
  {
    date: '2020.Q1 — 2020.Q3',
    title: 'Operation: BVP',
    role: 'Software Engineer, Full-Stack',
    scanId: 'BAV-OPS-19',
    objective:
      'Three employee groups. Three isolated portals. Zero stored passwords. Delivered a compliant pension management system where employees authenticate via email tokens, receive physical activation codes as printed PDF letters, and sync insurance records in bulk CSV batches from an external Prequity system — with React + Apollo GraphQL self-registration flows and no environment bleed.',
    tactics: [
      'Isolation by design — architected a domain-constrained multi-portal Rails 5.2 application with three independent SPA surfaces (DUK employee, AUPU employee, Employer) routed via subdomain constraints, each with fully isolated auth flows and access controls.',
      'No passwords, no exposure — implemented passwordless employee authentication via email sign-in tokens backed by a three-stage registration state machine (STARTED → EMAIL_CONFIRMED → COMPLETED), eliminating credential storage entirely.',
      'Physical identity, digitally enforced — built a postal verification pipeline where activation codes are generated as print-ready PDF letters via Prawn and mailed to employees, required before account activation can complete.',
      'Bulk sync without risk — engineered Prequity CSV batch synchronization (~2,000-record imports of insurance holders, contracts, and documents) via SmartCSV + ActiveRecord::Import with upsert logic and staging email interception to prevent environment bleed.',
      'Modern self-registration, validated at every step — delivered React 16 + Apollo GraphQL registration flows with Formik validation for contract numbers, email, and DOB; PgSearch-powered HR employee lookup with Pagy pagination.',
    ],
    outcome: '3 PORTALS. ZERO PASSWORDS.',
    tools: ['Rails 5.2', 'Ruby', 'React 16', 'Apollo GraphQL', 'PostgreSQL', 'Prawn', 'SmartCSV', 'PgSearch', 'Formik', 'Devise'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'left',
    imageUrl: 'images/bv.avif',
  },
  {
    date: '2020.Q3 — 2021.Q2',
    title: 'Operation: KEFIR',
    role: 'Software Engineer, Full-Stack',
    scanId: 'KP-OPS-20',
    objective:
      'Construction billing on paper creates gaps that cost money. Built a field operations platform that replaced manual workflows with role-enforced order tracking, real-time budget burn indicators (80% warning / 90% critical), and on-demand SAR/GAR financial report generation — backed by iScala ERP integration and a GitLab CI/CD pipeline with Kubernetes review environments on every feature branch.',
    tactics: [
      'Field-data flexibility at the schema level — architected a Rails 5.2 + React 16/Stimulus hybrid with Turbolinks-backed server rendering and React components backed by PostgreSQL hstore and JSONB for schema-free measurement data.',
      'Budget visibility before it\'s too late — built a real-time budget utilization engine tracking orders against defined thresholds with 80% warning and 90% critical indicators, giving project managers continuous visibility over active construction budgets.',
      'Access control that matches the org chart — implemented Pundit role-based authorization across four access tiers (admin, staff, gunvor, sophisticates_admin) with granular resource policies on every order, measurement, collection, and reporting action.',
      'Audit-ready financials on demand — delivered SAR and GAR financial reports as print-ready PDFs via Prawn/Prawn-Table and Excel exports via rubyXL, covering the full invoicing and audit trail for construction billing cycles.',
      'ERP-integrated pricing, CI-validated delivery — integrated iScala ERP product catalog with JSONB-tracked historical article pricing and measurement-level surcharge calculations; deployed via GitLab CI/CD with parallel RSpec + Capybara test stages and auto-deploy to Kubernetes review environments on feature branches.',
    ],
    outcome: 'PAPER BILLING ELIMINATED.',
    tools: ['Rails 5.2', 'Ruby', 'React 16', 'Stimulus', 'PostgreSQL', 'Pundit', 'Prawn', 'RubyXL', 'GitLab CI', 'Kubernetes', 'iScala ERP'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'right',
    imageUrl: 'images/kfr.avif',
  },
  {
    date: '2018.Q3 — 2019.Q2',
    title: 'Operation: M-Power',
    role: 'Software Engineer, Full-Stack',
    scanId: 'MP-OPS-18',
    objective:
      'Academic competitions across a four-tier organizational hierarchy — chambers, institutions, cohorts, teams — where score tampering can\'t happen and certificates need to generate automatically. Built an MD5-validated game session API with a Statesman state machine, Prawn certificate generation, RubyXL leaderboard exports, and a teacher test mode that lets admins preview contests without touching live rankings.',
    tactics: [
      'Org-wide access, precisely scoped — designed a four-tier STI group hierarchy (Admin → Chamber → Institution → Cohort) using Rails Single Table Inheritance, with Pundit policies enforcing role-specific visibility and management rights at every organizational boundary.',
      'Score integrity, enforced at the API level — built a game session API (POST /api/attempts to initialize, PUT /api/attempts/:token to submit) with MD5 checksum validation on every score submission, preventing client-side manipulation across all active contests.',
      'Seamless onboarding for every participant — implemented team token/password authentication for game client access; integrated Devise Invitable for teacher-to-student invitation flows and cohort self-enrollment via shared registration tokens.',
      'Results that prove themselves — delivered PDF certificate generation per team via Prawn and Excel statistics exports via RubyXL, covering leaderboards aggregated by chamber, institution, and level; included teacher test mode for out-of-competition trial runs.',
      'Production-grade reliability from the start — containerized with Docker + Docker Compose; deployed via Capistrano + Ansible; instrumented with Sentry and AppSignal for production error tracking and APM across the full competition lifecycle.',
    ],
    outcome: 'MD5-SEALED. FRAUD-PROOF.',
    tools: ['Rails', 'Ruby', 'PostgreSQL', 'Statesman', 'Pundit', 'Prawn', 'RubyXL', 'Docker', 'Capistrano', 'Ansible', 'Sentry', 'AppSignal'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'left',
    imageUrl: 'images/mp.avif',
  },
  {
    date: '2018.Q1 — 2018.Q4',
    title: 'Operation: News Desk',
    role: 'Software Engineer, Full-Stack',
    scanId: 'MND-OPS-18',
    objective:
      '167 models. 53 background workers. 71 service objects. 16 language markets. This is the scale of the press release platform where features were delivered, Grape REST endpoints maintained for third-party newsroom integrations, and social distribution kept live across Twitter, Facebook, LinkedIn, Instagram, and YouTube — while driving an Elasticsearch 6.5 migration from deprecated Solr under sustained publishing loads.',
    tactics: [
      'Publishing features at global scale — delivered across publish, network, analyze, and report namespaces of the Rails 5.2 monolith, contributing to press release management, multi-tenant hosted newsrooms, and audience analytics surfaces used by media organizations worldwide.',
      'Third-party integrations that just work — built and maintained Grape REST API endpoints powering newsroom integrations; extended multi-channel social distribution pipelines across Twitter, Facebook, LinkedIn, Instagram, and YouTube with consistent delivery guarantees.',
      'Async reliability under high-volume load — operated within the Sidekiq Pro ecosystem (53 background job types, sidekiq-cron) sustaining press release distribution, media monitoring ingestion from Twingly and GNIP, and SendGrid email delivery under sustained publishing pressure.',
      'Search modernization without disruption — drove Elasticsearch 6.5 query improvements as part of the migration from deprecated Solr 4.10, optimizing multi-locale content search across newsrooms at scale, with Redis and Memcache as layered caching.',
      'Shipped with confidence across a complex integration surface — operated within Buildkite CI/CD with Heroku review apps and an RSpec + VCR + Percy visual regression suite; integrated across Stripe, Salesforce, HubSpot, Segment, S3, and Cloudinary.',
    ],
    outcome: '16 MARKETS DISCOVERED.',
    tools: ['Rails 5.2', 'Ruby', 'Grape', 'Sidekiq Pro', 'Elasticsearch', 'Redis', 'Memcache', 'PostgreSQL', 'Buildkite', 'Heroku', 'Stripe', 'Salesforce', 'HubSpot', 'SendGrid'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'right',
    imageUrl: 'images/mnd.avif',
  },
  {
    date: '2019.Q1 — 2019.Q4',
    title: 'Operation: NJ-SIGN',
    role: 'Software Engineer, Full-Stack',
    scanId: 'NS-OPS-19',
    objective:
      'Legal contracts in the Japanese market require airtight security from template to finalized approval. Extended a digital signature platform with KMS-encrypted S3 document storage, blockchain hash recording on every approved contract, a multi-stage PDF pipeline (Prawn + CombinePDF + LibreOffice), and multi-provider OAuth for Google Drive, Slack, and Auth0 — every document action captured in a ShareLog audit trail.',
    tactics: [
      'Document security through every stage — engineered a document lifecycle state machine (init → draft → in_progress → approved/rejected → trashed) with owner/signer RBAC, subscription plan gating on contract limits, and hierarchical folder structures per team workspace.',
      'External signers without accounts — implemented polymorphic digital signature placement on both DocumentItem and TemplateItem models; built guest signer access via time-limited tokens and per-document password protection for secure external signing flows.',
      'Enterprise-grade document processing — built a multi-stage PDF pipeline (Prawn generation, CombinePDF merging, LibreOffice Word-to-PDF conversion) and executed a live S3 migration from Google Drive with AWS KMS encryption for document-at-rest security.',
      'Async reliability across every lifecycle event — wired Sidekiq + Redis workers across document mailers, blockchain hash recording for finalized contracts, Google Docs processing, and document sharing notifications.',
      'Connected to the tools teams already use — integrated multi-provider OAuth (Google Drive import/export, Slack channel sharing, Auth0) via OmniAuth; instrumented the ShareLog audit trail for full document distribution history and Sentry APM for production monitoring.',
    ],
    outcome: 'KMS-SEALED. CHAIN-ANCHORED.',
    tools: ['Rails', 'Ruby', 'PostgreSQL', 'AWS KMS', 'S3', 'Prawn', 'CombinePDF', 'LibreOffice', 'Sidekiq', 'Redis', 'Auth0', 'OmniAuth', 'Sentry'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'left',
    imageUrl: 'images/njs.avif',
  },
  {
    date: '2018.Q4 — 2019.Q2',
    title: 'Operation: Sophisticate',
    role: 'Software Engineer, Front-End',
    scanId: 'SOPH-OPS-19',
    objective:
      'No CMS. No database. No server. A digital strategy consultancy needed a high-performance portfolio site that editors could update without engineers. Delivered a Gatsby v2 static site with Markdown/YAML content, animated case study page transitions, keyboard navigation, project-level color themes, and PWA offline caching — containerized and shipped to staging and production Kubernetes via GitLab CI/CD.',
    tactics: [
      'Content managed in flat files, delivered at CDN speed — built a Gatsby v2 static site with React 16, a GraphQL data layer querying Markdown/YAML frontmatter, gatsby-image + Sharp for responsive optimized images, and Reactstrap/Bootstrap 4 for UI scaffolding.',
      'App-like case study browsing on a static site — implemented animated page transitions with direction tracking and keyboard navigation between project pages (← / → arrow keys), delivering fluid, interactive browsing without a backend.',
      'Editors work in Markdown, not dashboards — authored custom Markdown components (<reco>, <left>/<right>, <process>) for testimonials, two-column layouts, and step-lists, eliminating any CMS or database dependency for content updates.',
      'Brand identity, per project — delivered a theming system with radial gradient color palettes (rot, orange, grün, türkis, markenblau) applied dynamically to case study cards; wired PWA offline caching for instant repeat visits.',
      'Infrastructure-light, deployment-automated — containerized via multi-stage Docker build (Node 10 → Nginx Alpine) and deployed to staging and production Kubernetes via Helm through GitLab CI/CD.',
    ],
    outcome: 'ZERO CMS. KUBERNETES. PWA.',
    tools: ['Gatsby', 'React 16', 'GraphQL', 'PWA', 'Kubernetes', 'GitLab CI', 'Docker', 'Helm', 'Nginx', 'Bootstrap 4'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'right',
    imageUrl: 'images/sfts.avif',
  },
  {
    date: '2019.Q3 — 2020.Q2',
    title: 'Operation: Volt',
    role: 'Software Engineer, Full-Stack',
    scanId: 'VLT-OPS-19',
    objective:
      'Student loan fintech runs on payroll data, employer agreements, and legal precision — across systems that weren\'t built to talk to each other. Extended a three-application monorepo (Rails API, Ember.js borrower portal, React admin dashboard) with SAML SSO for Citizens, John Hancock, and Prudential; SOAP payroll connectors; AASM loan state machines; double-entry general ledger accounting; and Paper Trail audit logging.',
    tactics: [
      'Enterprise SSO and audit trails that hold up — extended the sl-pay Rails 5.2 backend across dual versioned APIs (/api/v1, /api/v2) with Devise + JWT auth, SAML SSO for Citizens, John Hancock, and Prudential, and AASM state machines for loan and payment lifecycle with Paper Trail audit logging.',
      'Payroll data where the platform needs it — built SOAP payroll connectors (JH/EPS/iPay) and Finicity financial data aggregation pipelines, bridging employer payroll into disbursement workflows alongside NSLDS student loan data synchronization.',
      'A borrower experience that scales across institutions — contributed to the Ember.js 3.8 portal implementing loan dashboard features, income-driven repayment flows, PSLF eligibility tools, and document e-signing with partner-specific multi-tenant theming per institutional brand.',
      'Admin tooling built for volume — extended the React 16 + Redux/Redux-Saga admin dashboard with employer/employee management surfaces, invoice generation, and bulk operation interfaces built on Material-UI and DevExtreme data grids.',
      'Reliable, observable, and production-ready — maintained Sidekiq background job pipelines for email, reports, and batch processing; instrumented Sentry and LogRocket across all three applications; shipped via CircleCI with Docker and S3 + CloudFront deployments.',
    ],
    outcome: 'SAML. SOAP. ACH. ONE REPO.',
    tools: ['Rails 5.2', 'Ruby', 'Ember.js 3.8', 'React 16', 'Redux', 'Redux-Saga', 'SAML', 'JWT', 'Sidekiq', 'CircleCI', 'Docker', 'Sentry', 'LogRocket', 'AWS S3', 'CloudFront'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'left',
    imageUrl: 'images/vlt.avif',
  },
  {
    date: '2019.Q4 — 2020.Q3',
    title: 'Operation: SecureAuth',
    role: 'Team Lead | Software Engineer, Full-Stack',
    scanId: 'SAI-OPS-19',
    objective:
      'Enterprise identity is the most expensive thing to get wrong. Operated across a 9-component IAM platform — Ruby auth APIs, React admin portals, Node.js middleware, C# .NET Identity Provider core — hardening adaptive risk policies with BehavioSec behavioral biometrics, HMAC-SHA256 signed requests with replay-attack prevention, Argon2 password hashing, and federated SSO across SAML, OAuth 2.0, OpenID Connect, CAS, and Kerberos.',
    tactics: [
      'Auth APIs hardened against replay and brute force — extended the Ruby/Sinatra+Grape authentication service (rupert) and Admin REST API (twilight) with MFA policy endpoints, HMAC-SHA256 request signing with replay-attack prevention via timestamp validation and memory cache, and Argon2 password hashing.',
      'Risk-based auth that adapts to the threat — maintained adaptive risk logic including BehavioSec behavioral biometrics, device fingerprinting, geographic/IP policy enforcement, and threat detection integrations with Exabeam and Cisco pxGrid for configurable conditional auth policies.',
      'Admin control surfaces across the full IAM surface — contributed to three React admin portals (spike, coruscant, dagobah) and Node.js middleware (bespin) for realm, application, and data store management with full RBAC and audit logging.',
      'SSO that works with every enterprise standard — maintained federated flows across SAML 1.1/2.0, OAuth 2.0, OpenID Connect, CAS, and Kerberos/SPNEGO; secured credentials via CyberArk Vault, encrypted fields, and RS256/HS256-signed JWTs with rate limiting and account lockout.',
      'Documented, tested, and deployable across stacks — authored Swagger/OpenAPI 3.0 and Protobuf contracts across all nine services; maintained Jenkins + Artifactory CI/CD with Jest/Enzyme, RSpec + Rubocop, and NUnit coverage across Ruby, React, and C# components.',
    ],
    outcome: 'BIOMETRIC AUTH. ZERO TRUST.',
    tools: ['Ruby', 'Sinatra', 'Grape', 'React', 'Node.js', 'C# .NET', 'SAML', 'OAuth 2.0', 'OpenID Connect', 'JWT', 'CyberArk', 'Jenkins', 'BehavioSec', 'RSpec', 'Jest'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'right',
    imageUrl: 'images/sat.avif',
  },
  {
    date: '2017.Q1 — 2018.Q1',
    title: 'Operation: Energy Cloud',
    role: 'Software Engineer, Full-Stack',
    scanId: 'EC-OPS-17',
    objective:
      'LED lighting retrofits involve hundreds of fixtures, complex ROI math, and multi-supplier procurement — every step of which used to be manual. Built a B2B SaaS that automates the full audit lifecycle: algorithm-driven fixture matching across 17 command classes, energy savings and payback period analysis, PDF quote generation, Zoho subscription billing, and multi-supplier purchase orders with EasyPost shipping validation.',
    tactics: [
      'Replacement recommendations, automated — built the core audit hierarchy (Audits → Areas → Legacy Fixtures) with photo annotation support and a matching algorithm across 17 Mutations gem command classes, automatically pairing legacy fixtures to LED products by lamp shape, base, voltage, lumens, and kelvin.',
      'Financials that close deals — developed a financial analysis engine calculating energy savings, ROI, payback period, and financing options per audit; generated professional PDF quotes and signed audit reports via WickedPDF + wkhtmltopdf for customer-facing deliverables.',
      'Catalog at scale, imported fast — built a multi-supplier product catalog with bulk Excel/CSV import via Roo gem and real-time import progress via ActionCable WebSockets; managed async Sidekiq jobs for long-running imports and image processing against PostgreSQL and Paperclip storage.',
      'Subscriptions that manage themselves — integrated Zoho Subscriptions webhook pipeline for automated subscription lifecycle (activations, upgrades, cancellations) automatically toggling roles and permissions via CanCanCan + RoleModel RBAC across Auditors, Suppliers, Admins, and Invitors.',
      'From audit to shipped order — delivered multi-supplier purchase order generation with EasyPost shipping address validation; maintained an ActiveAdmin panel for platform management; deployed via Capistrano + Passenger on DigitalOcean with Honeybadger error tracking across a 113-migration PostgreSQL schema.',
    ],
    outcome: 'FIELD AUDIT → PURCHASE ORDER.',
    tools: ['Rails', 'Ruby', 'PostgreSQL', 'Sidekiq', 'ActionCable', 'WickedPDF', 'Zoho', 'EasyPost', 'ActiveAdmin', 'CanCanCan', 'Capistrano'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'left',
    imageUrl: 'images/nrg.avif',
  },
  {
    date: '2017.Q3 — 2018.Q2',
    title: 'Operation: 5NGo',
    role: 'Software Engineer, Back-End',
    scanId: 'FNG-OPS-17',
    objective:
      'Real-world social games require geospatial precision, Redis-powered matchmaking, and QR code presence validation to confirm people actually showed up. Built the full JSON API backend for a location-based game where strangers meet in PostGIS zones, scan QR codes, and co-author geotagged stories — backed by a six-stage state machine, DCI architecture, and ActionCable WebSocket delivery for iOS and Android.',
    tactics: [
      'Physical presence, cryptographically confirmed — built the game state machine (assigned → started → confirmed → created → finished/failed) with PostGIS geographic zone management, time-window activation, meetup point assignment, QR code confirmation, and story/scenario prompt sequencing per zone.',
      'Pairs matched in milliseconds, bad actors excluded — engineered a Redis-backed real-time matchmaking engine queuing players per game zone and pairing by experience category (newby/experience/sponsored) with blocked/reported user exclusion; delivered live game state via ActionCable WebSockets (NotificationChannel, CommonChannel).',
      'Business logic isolated, contexts composable — implemented DCI architecture via the dci gem organizing matchmaking, creation upload, and zone lifecycle into dedicated app/context/create_mode/ contexts; wired rpush (APNS/FCM) push notifications for all game flow events.',
      'API versioned, documented, and auth-locked — delivered a versioned JSON API (versionist, Accept header routing) across create_mode, explore_mode, users, game_zones, likes, reports, and blocks namespaces with Devise + custom token auth, Facebook Account Kit social login, and Swagger documentation.',
      'Background jobs with purpose — deployed Sidekiq workers across five dedicated queues (default, mailers, create_mode, game_zone, online_statistics) with Clockwork scheduled tasks; managed CarrierWave + fog-aws S3 uploads for geotagged creations; maintained ActiveAdmin + CanCanCan panel for zone, story, and user moderation.',
    ],
    outcome: 'GPS-MATCHED. QR-CONFIRMED.',
    tools: ['Rails', 'Ruby', 'PostgreSQL', 'PostGIS', 'Redis', 'ActionCable', 'Sidekiq', 'Clockwork', 'Swagger', 'FCM', 'APNS', 'CarrierWave', 'AWS S3'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'right',
    imageUrl: 'images/5nG.avif',
  },
  {
    date: '2016.Q4 — 2017.Q3',
    title: 'Operation: Half Cost Hotels',
    role: 'Software Engineer, Back-End',
    scanId: 'HCH-OPS-16',
    objective:
      'Last-minute hotel bookings run on precision timing — holds expire, payments split across gateways, and hotel payouts need to happen automatically overnight. Built the complete REST API backend for a discount platform with three concurrent AASM state machines, dual-gateway payments (Braintree for guests, Dwolla ACH for hotels), custom PostgreSQL pricing functions for dynamic discounts, and a dual-namespace API for managers and customers on mobile and web.',
    tactics: [
      'Thin controllers, pure business logic — designed DCI architecture with ~111 single-use Context objects (.perform()) encapsulating booking holds, payment flows, payout initiation, and subscription billing per use case.',
      'Three lifecycles, zero conflicts — implemented concurrent AASM state machines for Booking (on_hold → waiting_for_payment → upcoming → current → past), Subscription (pending → active → past_due → canceled), and Payout (created → processing → done/failed), with 15-minute hold expiration enforced via Sidekiq-Cron.',
      'Guests pay one way, hotels get paid another — built dual-gateway payment infrastructure with Braintree for customer subscription billing and saved card management, and Dwolla for automated ACH hotel earnings payouts, driven by hourly Sidekiq-Cron reconciliation jobs.',
      'Pricing that reflects real availability — implemented custom PostgreSQL pricing functions (hotel_discount(), discounted_price()) for dynamic first-night and per-night discount computation; delivered a hotel search engine (price, dates, rating, amenities, beds, parking, dining) with cursor-based pagination.',
      'Two audiences, one codebase — delivered a dual-namespace versioned JSON API (/api/v1/managers, /api/v1/customers) with custom TokenAuth + Facebook/Google OAuth; wired Firebase Cloud Messaging push, ActionCable WebSocket, and SMTP via a polymorphic Notification model; deployed via Dokku + Puma.',
    ],
    outcome: 'BRAINTREE + DWOLLA. 3 MACHINES.',
    tools: ['Rails', 'Ruby', 'PostgreSQL', 'AASM', 'Braintree', 'Dwolla', 'Sidekiq', 'Firebase', 'ActionCable', 'Devise', 'Dokku'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'left',
    imageUrl: 'images/htl.avif',
  },
  {
    date: '2015.Q4 — 2016.Q3',
    title: 'Operation: Inviteez', // TODO: hide project name
    role: 'Software Engineer, Back-End',
    scanId: 'INV-OPS-15',
    objective:
      'Event apps live or die on the ability to reach people who aren\'t registered yet. Built a mobile invitation platform with shadow account infrastructure for non-registered invitees, phone-first SMS authentication via Nexmo + Doorkeeper OAuth, real-time event chat, MD5 duplicate detection on photo albums, and 15+ push notification types delivered via Rpush APNS to iOS-first clients.',
    tactics: [
      'Invitations that reach anyone — built a full event management and smart invitation API supporting registered users, phone/email contacts, and token-based invite links; implemented shadow accounts for non-registered invitees and RSVP status tracking (accepted/declined/no reply) across the invitation lifecycle.',
      'Phone-first auth, policy-enforced access — architected phone-first authentication via Nexmo SMS verification + Doorkeeper OAuth 2.0 password grant with token/refresh flow; enforced Pundit policy-based authorization across all event, invitation, chat, and album resources.',
      'Rich engagement without complexity — delivered event chat with JSON-structured messages, embedded photo support, and per-user read state; built per-event photo albums with MD5 duplicate detection and CarrierWave + MiniMagick image processing via Sidekiq background workers.',
      '15+ notification types, one model — implemented an STI-based Notification model consolidating all notification types in a single table, backed by Rpush APNS push delivery for iOS; wired Sidekiq + Whenever cron for scheduled RSVP reminder dispatch across active events.',
      'Versioned, audited, and production-ready — shipped a versioned JSON-API (V1 full, V2 limited) via Versionist + ActiveModel Serializers with soft-delete archiving (deleted_at) across all records; instrumented with Rollbar error tracking, New Relic APM, and Mandrill transactional email.',
    ],
    outcome: 'LIVE UPDATES. SHADOW ACCOUNTS.',
    tools: ['Rails', 'Ruby', 'PostgreSQL', 'Doorkeeper', 'OAuth 2.0', 'Pundit', 'Nexmo', 'Rpush', 'Sidekiq', 'Rollbar', 'NewRelic', 'Mandrill'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'right',
    imageUrl: 'images/evnt.avif',
  },
  {
    date: '2016.Q3 — 2017.Q2',
    title: 'Operation: The Walk',
    role: 'Software Engineer, Back-End',
    scanId: 'TW-OPS-16',
    objective:
      'Six content types. Four media formats. Four OAuth providers. Three Bible translations. One Swagger-documented versioned Rails 5 API — serving personalized spiritual content to a global mobile and web audience. Integrated Contentful CMS for bulk import, AWS Elastic Transcoder for video conversion, and a four-job async media pipeline, with topic-interest content feeds and per-user translation preferences built in.',
    tactics: [
      'Every content type, one consistent API — designed a versioned Rails 5 JSON API across 21 service classes, 20 serializers, and 19 controllers, with polymorphic Favorites, Follows, Notes, and Views spanning Teachings, Prayers, Bible Passages, Topics, Authors, and Organizations via concern-based mixins.',
      'Content imported at scale, not entered by hand — integrated Contentful CMS for bulk sync of video/audio Teachings, multi-step guided Prayers, and multi-translation Bible Passages (NIV/ESV/NLT) into PostgreSQL via Sidekiq background workers.',
      'Media in the right format, served from the edge — built a four-job async media pipeline: FFmpeg server-side transcoding, AWS Elastic Transcoder format conversion, and Tinify image compression, serving processed assets via AWS S3 + CloudFront CDN.',
      'Personalized discovery, for any believer — implemented Challah gem authentication with guest user support and four OAuth providers (Facebook, Google, Instagram, Twitter); delivered personalized topic-interest feeds, per-user Bible translation preferences, and full-text PostgreSQL search.',
      'Documentation and test coverage that ship with confidence — documented all endpoints with Swagger; maintained 40+ API integration test specs via RSpec + FactoryBot + VCR across 92+ PostgreSQL migrations; managed content via ActiveAdmin (ArcticAdmin theme) backed by Sidekiq + Redis.',
    ],
    outcome: 'GLOBAL SPIRIT PERSISTENCE.',
    tools: ['Rails 5', 'Ruby', 'PostgreSQL', 'Sidekiq', 'Redis', 'Contentful', 'AWS S3', 'CloudFront', 'FFmpeg', 'Tinify', 'Swagger', 'ActiveAdmin'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'left',
    imageUrl: 'images/twlk.avif',
  },
  {
    date: '2016.Q1 — 2016.Q4',
    title: 'Operation: Staffing',
    role: 'Software Engineer, Back-End',
    scanId: 'SP-OPS-16',
    objective:
      'Every hire runs two state machines simultaneously — one tracking the candidate, one tracking the manager — and neither can see the other\'s status until the right moment. Built a DCI-pattern recruitment API with 38+ context classes, STI-based user hierarchy, video introduction processing via FFmpeg, four notification channels (push, email, in-app, YoChat), and Stripe premium features — Swagger-documented and shipped via GitLab CI/CD.',
    tactics: [
      'Business logic that never bleeds into controllers — designed DCI architecture with 38+ context classes delegating all logic (profile management, application transitions, company verification, vacancy matching) to dedicated context objects, keeping the codebase isolated and testable across 99 RSpec spec files.',
      'Two sides of every hire, tracked independently — engineered STI-based user hierarchy (User → Candidate/Manager) with dual state machines (candidate: matching → applied → declined; manager: pending → shortlisted → rejected) and a polymorphic feed model for personalized vacancy + post streams.',
      'Profiles that prove experience — built candidate profiles covering work history, education, trainings, languages, photos, and video introductions via FFmpeg, with CarrierWave + AWS S3 storage and employer job-history verification workflows.',
      'Notifications everywhere candidates and employers live — integrated Stripe payment pipeline for premium features; delivered four notification channels (in-app, Rpush iOS/Android push, Mandrill email, YoChat messaging) across application, social, and company events.',
      'API-first, documented, and continuously deployed — shipped a versioned JSON API (/api/v1/ via Accept header) with stateless bearer token auth, CanCan authorization, Facebook/Instagram/Twitter OAuth login, and SwaggerEngine OpenAPI 2.0 docs; deployed via Capistrano 3 + Puma + Nginx with GitLab CI/CD across 146 PostgreSQL migrations.',
    ],
    outcome: 'DUAL-TRACKED. VIDEO-VERIFIED. HIRED.',
    tools: ['Rails', 'Ruby', 'PostgreSQL', 'Devise', 'Stripe', 'FFmpeg', 'CarrierWave', 'AWS S3', 'Rpush', 'Mandrill', 'Capistrano', 'GitLab CI'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'right',
    imageUrl: 'images/stf.avif',
  },
  {
    date: '2015.Q3 — 2016.Q2',
    title: 'Operation: VoVi',
    role: 'Software Engineer, Back-End',
    scanId: 'VV-OPS-15',
    objective:
      'Educational content arrives in four formats — video, audio, text, image — and every format has different storage, metadata, and delivery requirements. Built the API backend and admin CMS for a multi-format lesson platform with DCI context classes for discovery and filtering, S3-hosted MP3 audio, Rpush push notifications for iOS/Android, and Stripe subscriptions — deployed across three environments via Capistrano + GitLab CI.',
    tactics: [
      'Content discovery that feels instant — designed DCI context classes (FindLessons, SearchLessonsByTitle, GetFilteredLessons) for lesson discovery, full-text title search, quality/year filtering, and featured recommendations, with AMS serializers across paginated, category-filtered, and ID-list endpoints.',
      'Every format, the right storage — built a multi-format lesson model with nested YouTube video URLs, S3-hosted MP3 audio (CarrierWave + fog-aws), uploaded text documents, and images, with metadata tracking (location, quality, date), category organization, and view count increment via PATCH /api/lessons/:id.',
      'Push that works across platforms — wired Rpush APNS + GCM/FCM push notification pipeline with Sidekiq background workers, handling iOS/Android device registration and async notification delivery alongside YouTube video duration fetching and audio metadata extraction jobs.',
      'Revenue and social built in — integrated Stripe payment pipeline for subscription features; implemented Facebook/Instagram/Twitter/Google/YouTube OAuth social integrations via Koala for user authentication and content discovery.',
      'Three environments, one deployment story — deployed across production/staging/dev via Capistrano 3 + Puma + Nginx with shared .env secrets, preserved upload/log directories across releases, daily CarrierWave cache cleanup cron, and GitLab CI; managed content via ActiveAdmin with full CRUD, batch operations, and media upload support.',
    ],
    outcome: 'VIDEO. AUDIO. TEXT. IMAGE. DELIVERED.',
    tools: ['Rails', 'Ruby', 'PostgreSQL', 'Sidekiq', 'Stripe', 'CarrierWave', 'AWS S3', 'Rpush', 'ActiveAdmin', 'Capistrano', 'GitLab CI'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'left',
    imageUrl: 'images/vv.avif',
  },
  {
    date: '2015.Q1 — 2015.Q4',
    title: 'Operation: Yalta',
    role: 'Software Engineer, Full-Stack',
    scanId: 'YW-OPS-15',
    objective:
      'A mobile agency\'s website needs to impress prospects and convert them — every time. Built a block-based article platform with five reader reactions, YAML-driven portfolio content, Pipedrive CRM integration on every contact form, Mailchimp newsletter subscriptions, referrer trail tracking, and Mixpanel behavioral analytics — with Redis caching and a multi-role publishing workflow for publisher, admin, and superadmin operators.',
    tactics: [
      'Editorial content that editors actually control — built a block-based article publishing system with draft/published state management, STI-based block types (Blocks::CallToAction, Blocks::ArticleBlock via the actable gem), a five-reaction reader engagement system (Wow/Mmm/Hmm/Meh/Pff), per-article view tracking by IP + user agent, and RSS feed generation.',
      'Portfolio updates without migrations — implemented YAML-based static content models for portfolio case studies (/data/works/) and technology showcases (/data/technologies/), enabling content updates without database migrations while maintaining flexible layout, industry segment categorization, and tagging.',
      'Every visitor a potential lead — integrated Pipedrive CRM lead pipeline via contact/estimation forms with file upload, budget selection, NDA agreement, and honeypot spam protection; included CSV export and ActionMailer email notifications converting site visitors into managed sales opportunities.',
      'Behavioral insight baked in from day one — built multi-session referrer trail tracking for user journey analytics; integrated Mailchimp API for category-based newsletter subscriptions; wired Google Analytics, Mixpanel, Hotjar, and Twitter API for social share count aggregation.',
      'Performance and reliability without overhead — applied Draper decorator pattern for view logic separation; managed Redis caching (5-min TTL) + Rack HTTP-level caching; shipped Sidekiq workers for report generation and mailers with Whenever daily sitemap cron; deployed via Capistrano 3 + RVM with CanCanCan RBAC across the ActiveAdmin panel.',
    ],
    outcome: 'EVERY VISITOR. PIPEDRIVE-READY.',
    tools: ['Rails', 'Ruby', 'Redis', 'Sidekiq', 'Pipedrive', 'Mailchimp', 'Mixpanel', 'Google Analytics', 'Hotjar', 'CanCanCan', 'ActiveAdmin'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    isGhost: true,
    align: 'right',
  },
  {
    date: '2015.Q2 — 2016.Q2',
    title: 'Operation: LoopMe',
    role: 'Software Engineer, Full-Stack',
    scanId: 'LM-OPS-15',
    objective:
      'Ad tech at scale means Kafka event streams, Redshift analytics warehousing, 40+ ad formats, 18 network integrations, and 12 RBAC roles all running in parallel across five production environments. Extended a large-scale Rails monolith with campaign lifecycle management, multi-dimensional reporting dashboards, affiliate commission accounting, and a REST partner API — sustaining RTB throughput and analytics delivery under high-volume advertising loads.',
    tactics: [
      'Campaign management for every format and audience — extended campaign and line item management across 40+ ad formats (banners, fullscreen, MPU, VAST/VPAID video) with budget controls, frequency capping, A/B testing with control groups, geo/device/carrier/app-category targeting, and creative CRUD stored via CarrierWave + S3 + CloudFront CDN.',
      '18 networks, one integration standard — maintained 18 ad network API integrations (MoPub, Fyber, and 16 others) and a public REST API (/api/v1/) for external partner access to campaigns, line items, creatives, and reports; supported four pricing models (CPC, CPI, CPM, CPCV) across advertiser and affiliate billing flows.',
      'Analytics that answer before you ask — built multi-dimensional reporting dashboards with real-time KPI views (7-day and 2-day aggregations), Elasticsearch-backed large-scale queries, and Highcharts visualizations, with CSV export and scheduled email report delivery; backed by 29 statistics models and Redis caching with Sidekiq recalculation workers.',
      'Every dollar tracked, every affiliate reconciled — operated invoicing, billing log, balance tracking, and monthly reconciliation workflows across event-level cost pipelines driven by Apache Kafka streaming; managed affiliate earnings accounting alongside advertiser CPC/CPI/CPM spend — with Redshift as the analytics warehouse.',
      '12 roles, 5 environments, full observability — enforced acl9 RBAC across 12 user roles with admin account impersonation; applied Draper decorator pattern for view logic separation; maintained Datadog StatsD, New Relic, and Sentry observability across Docker + Puma + Consul (service discovery) in five environments.',
    ],
    outcome: 'KAFKA. 40+ AD FORMATS. 18 NETS.',
    tools: ['Rails', 'Ruby', 'PostgreSQL', 'Elasticsearch', 'Apache Kafka', 'Redshift', 'Redis', 'Sidekiq', 'Highcharts', 'Docker', 'Datadog', 'NewRelic', 'Sentry'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'left',
    imageUrl: 'images/lpm.webp',
  },
  {
    date: '2014.Q3 — 2015.Q2',
    title: 'Operation: Gambitious',
    role: 'Software Engineer, Full-Stack',
    scanId: 'GMB-OPS-14',
    objective:
      'European equity crowdfunding means KYC identity verification, legally binding e-signatures, SOAP payment gateways, 21% VAT, and four campaign types in the same state machine. Extended a mature Rails monolith (52 models, 35 controllers, 26 service objects) with AASM-driven campaign flows, RightSignature legal agreements, Prooflink KYC verification, and a custom FEET SOAP gateway (~11K LOC) — under Dutch regulatory requirements.',
    tactics: [
      'Four campaign types, one state machine — extended AASM-managed Idea state machines (created → pending_review → active → fully_funded/missed_deadline) across four STI subtypes (equity, pledge, hybrid, charity) with 26 service objects handling payment orchestration, notifications, onboarding, and Delayed Job + Whenever reminder workflows.',
      'Payments that survive regulatory scrutiny — integrated the FEET SOAP payment gateway (custom lib/feet.rb, ~11K LOC) via Savon + IBAN-Tools for primary EUR payment processing; maintained PayPal legacy support; implemented Money-Rails EUR denomination with tiered transaction fees (2.5% / 1%) and EU 21% VAT compliance.',
      'Legal agreements that hold up in court — wired RightSignature for legally binding e-signatures on equity investment agreements; integrated Prooflink for KYC/identity verification of equity investors; generated PDF invoices via Princely; managed file and image storage via CarrierWave + MiniMagick + AWS S3 (Fog).',
      'Complex investor flows made navigable — maintained a full-stack HAML view layer with Draper decorators and form objects for investor input flows; implemented Observer-pattern NotificationObserver triggering 9 mailers on model state changes, with English/Dutch I18n across Amsterdam timezone configuration.',
      'Marketing, compliance, and deployment squared away — integrated Campaign Monitor for email marketing and investor newsletters; deployed via Capistrano 3 + RVM + Unicorn; maintained Airbrake error tracking; covered the codebase with Test::Unit + RSpec across a MySQL-backed schema.',
    ],
    outcome: 'KYC. E-SIGN. EU VAT. 4 MODES.',
    tools: ['Rails', 'Ruby', 'MySQL', 'AASM', 'RightSignature', 'Prooflink', 'PayPal', 'Savon', 'CarrierWave', 'AWS S3', 'Capistrano', 'RSpec'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'right',
    imageUrl: 'images/gmb.avif',
  },
  {
    date: '2014.Q2 — 2014.Q4',
    title: 'Operation: NenCrowd',
    role: 'Software Engineer, Full-Stack',
    scanId: 'NEN-OPS-14',
    objective:
      'Dutch crowdfunding requires iDEAL banking, bilingual routes, corporate vs. individual investor validation, and transactional email triggers — all inside the same four-step wizard. Built a Reform-validated investment flow with a custom Buckaroo iDEAL gateway, JSONP embeddable project widgets, Traco column-per-locale i18n, and a service object layer — compliant with Amsterdam timezone and Dutch regulatory requirements.',
    tactics: [
      'A four-step wizard that handles every investor type — built a four-step investment flow (reward selection → personal data → payment → confirmation) using Reform form objects with conditional validation for individual vs. corporate investors, managing session-based wizard state and JSONP embeddable widget endpoints for external sites.',
      'iDEAL payments with tamper-proof confirmation — integrated the Buckaroo payment gateway via a custom lib/buckaroo/ library supporting iDEAL Dutch banking, credit card, and invoice payment methods with signature-based webhook callback validation.',
      'Engagement beyond the investment — delivered AJAX-based infinite scroll for project comments and updates; built per-project and site-wide newsletter subscription management; integrated BettyBlocks API to trigger transactional emails on investment creation, comment activity, and project update publication.',
      'Two languages, one URL structure — implemented Traco column-per-locale model-level i18n and Route Translator for bilingual URL routing (/nl/, /en/); applied Draper decorator pattern across Slim + SASS + CoffeeScript frontend templates with Turbolinks navigation.',
      'Business logic encapsulated, not scattered — encapsulated all business logic in dedicated service objects (InvestmentCreator, TransactionProcessor, UserCreator, BettyActionEffectuator); deployed via Capistrano across a Rails 4.1 + MySQL stack targeting Dutch regulatory requirements.',
    ],
    outcome: 'iDEAL-POWERED. BILINGUAL. EU.',
    tools: ['Rails 4.1', 'Ruby', 'MySQL', 'Reform', 'Buckaroo', 'Sidekiq', 'Traco', 'CoffeeScript', 'Slim', 'Capistrano'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'left',
    imageUrl: 'images/nen.avif',
  },
  {
    date: '2013.Q3 — 2014.Q3',
    title: 'Operation: NowShop',
    role: 'Software Engineer, Full-Stack',
    scanId: 'NOW-OPS-13',
    objective:
      'Scandinavian retail multi-tenancy means dozens of carrier subdomains, automatic cart splitting per retailer, per-category commission calculations, and a PayPal stack covering Express Checkout, IPN, Adaptive Accounts, and billing agreements — all in the same request cycle. Extended a complex Rails 4 marketplace (58+ models, 11 query objects) serving smartguy.dk, boozt.com, and coolshop.com — with GeoIP localization, multi-currency, and FTP-based bulk product imports.',
    tactics: [
      'Subdomain routing that scales to any carrier — extended multi-tenancy via CarrierDetector middleware routing carrier contexts through namespaced controllers (Admin/Carrier/Retailer/Public/API); maintained 58+ models and 11 query objects across a product master/variant hierarchy with SKU deduplication and FTP bulk import feed processing.',
      'Mixed carts, cleanly split — built automatic cart order splitting by retailer, decomposing mixed-cart purchases into separate payment flows per vendor, with custom order state machines (pending → processing → shipped → completed) and per-retailer/per-category commission calculation and reporting.',
      'PayPal at every stage of the transaction — integrated PayPal Express Checkout, IPN notifications, Adaptive Accounts, and billing agreements via a dedicated Payment::PayPal service layer; maintained Pensio gateway support; built a REST Order webhook API (v1) for retailer integrations with tokenizable record access.',
      'Right content for every location — delivered GeoIP detection for geographic localization, multi-currency support, and country-specific shipping logic; managed AlchemyCMS 3.0 for carrier page building and media management; scheduled product feed processing, commission calculations, and exchange rate updates via Whenever cron.',
      'Backbone.js frontend, production-grade observability — built a Backbone.js + jQuery + CoffeeScript frontend on Bootstrap SASS; maintained NewRelic APM and Airbrake error tracking; covered the platform with RSpec + Capybara + Factory Girl across a PostgreSQL schema with hstore and enforced foreign keys.',
    ],
    outcome: 'BOOZT. COOLSHOP. SMARTGUY. UNIFIED.',
    tools: ['Rails 4', 'Ruby', 'PostgreSQL', 'PayPal', 'Backbone.js', 'jQuery', 'CoffeeScript', 'Bootstrap', 'AlchemyCMS', 'NewRelic', 'RSpec', 'Capybara'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'right',
    imageUrl: 'images/nw.avif',
  },
  {
    date: '2014.Q4 — 2015.Q4',
    title: 'Operation: Revolution',
    role: 'Software Engineer, Full-Stack',
    scanId: 'R9-OPS-14',
    objective:
      'Musicians and artists want a professional website — not a development project. Built a SaaS CMS where artists get a live site on their own domain, designed through a Liquid template editor, styled with Adobe Typekit fonts, and billed via Adyen recurring subscriptions — with Campaign Monitor fan email capture and a Custom Domain constraint class routing every request to the right artist\'s site.',
    tactics: [
      'Any domain, the right artist, every time — engineered multi-domain routing via a Custom Domain constraint class resolving incoming requests to the correct artist CMS context by subdomain or custom domain; maintained 48 ActiveRecord models across content domains (albums, tracks, tour dates, photo albums, blog posts, news, video pages) with CarrierWave + MiniMagick + Fog cloud media storage.',
      'Full design control, no code required — built a Liquid template rendering pipeline exposing layout, page, menu, resource, and partial template editors alongside a custom CSS/JS editor, Adobe Typekit font integration, and a visual design mode for hero imagery and color themes; backed by a service layer for CMS rendering and design mode logic.',
      'Subscriptions that run themselves — integrated Adyen recurring payment processing handling tiered subscription plans with visitor/feature limits, trial periods, upgrade/downgrade flows, and billing agreement management; automated expiration checks and payment status reconciliation via Delayed Job + Whenever cron.',
      'Fan relationships built into the platform — delivered Campaign Monitor (CreateSend) integration for email capture and list management, a comment system across blog/news/video content types, visitor tracking, and social media profile link management (Spotify, iTunes, YouTube, and more).',
      'Admin operations at scale, reliably delivered — maintained a HAML/Slim admin view layer across 27 controllers with Devise authentication; applied Dalli (Memcached) caching for CMS rendering throughput; covered the platform with RSpec + Factory Girl + Capybara; deployed via Capistrano 3 + Monit on MySQL-backed Rails 4.0 + Ruby 2.1.5.',
    ],
    outcome: 'ANY DOMAIN. LIQUID. NO CODE.',
    tools: ['Rails 4', 'Ruby', 'MySQL', 'Liquid', 'Adyen', 'Delayed Job', 'Dalli', 'Memcached', 'CarrierWave', 'Capistrano', 'RSpec', 'Devise'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'left',
    imageUrl: 'images/rv.avif',
  },
  {
    date: '2013.Q2 — 2013.Q4',
    title: 'Operation: Disco',
    role: 'Software Engineer, Full-Stack',
    scanId: 'D4Y-OPS-13',
    objective:
      'A furniture retailer needed an online catalog that could handle product attributes that don\'t fit standard e-commerce schemas — sleep places, clothing boxes, mechanisms, dimensions. Delivered a Rails 3.2 catalog with 9 domain models, Google Maps integration, AJAX cart foundations, and dual admin interfaces — deployed to production via Capistrano remote-cache strategy.',
    tactics: [
      'Domain model built for furniture, not generic products — modelled 9 core domain entities (Product, Category, User, Comment, Country, Factory, Type, Model, Metum) capturing furniture-specific attributes with Paperclip image attachments and Kaminari/will_paginate pagination (6 products per page in production).',
      'Product discovery beyond keyword search — implemented a category-browsable catalog with detail pages, similar product recommendations, a CommonDefines shared module for consistent page parameter validation across controllers, and GMaps4Rails (Google Maps) for location-aware pages.',
      'Cart and auth ready from day one — built AJAX-based shopping cart foundations (BasketController, AjaxController) with Devise authentication — registration, login, and password recovery flows — and static informational pages (how to buy, warranty, shipping, about, contacts).',
      'Two admin panels, one data set — mounted RailsAdmin + ActiveAdmin at /admin for content and product data management; deployed via Capistrano + RVM remote-cache strategy with symlinked database.yml, uploads/, and system/ directories on a MySQL-backed production VPS.',
    ],
    outcome: 'MAPS. DUAL ADMIN. CART READY.',
    tools: ['Rails 3.2', 'Ruby', 'MySQL', 'Devise', 'Paperclip', 'GMaps4Rails', 'ActiveAdmin', 'RailsAdmin', 'Capistrano'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'right',
    imageUrl: 'images/df.webp',
  },
  {
    date: '2014.Q3 — 2016.Q1',
    title: 'Operation: Kyiv',
    role: 'Software Engineer, Full-Stack',
    scanId: 'KGA-OPS-14',
    objective:
      'Kyiv tourism content needs to stay current — hotels change, venues move, and accuracy across four languages is non-negotiable. Built a multilingual city guide with a live Feratel XML sync pipeline keeping accommodation data continuously reconciled from interface.deskline.net, GPS-mapped venues across all content types, Thinking Sphinx full-text search, and BrowserCMS editorial tools — serving English, Ukrainian, Russian, and German audiences.',
    tactics: [
      'Four languages, one schema — implemented Globalize3 DB-backed translations across all content models (tourism places, food venues, events, carriers, news, accommodation), serving four locales (EN/UK/RU/DE) with locale-aware routing and editorial workflows.',
      'Hotel data that stays in sync automatically — built a Feratel accommodation sync pipeline using LibXML-Ruby to parse XML feeds from interface.deskline.net; UpdateAccommodationDataWorker and GetKeyValuesWorker scheduled via Sidekiq 2 + sidekiq-cron to keep hotel/hostel data (star ratings, facilities, classifications) continuously reconciled.',
      'Every venue on the map, every asset processed — delivered geolocation-enabled content across tourism places, food venues, events, and carriers with GPS coordinates stored per entity and rendered via gmaps4rails (Google Maps); managed Paperclip + FFmpeg media pipelines for image and video asset handling.',
      'Content found, cache invalidated cleanly — integrated Thinking Sphinx 3 full-text search across all content types; built BrowserCMS portlet system for modular editorial blocks (carousels, banners, booking widgets, social tabs); implemented fragment caching with a dedicated CacheResetController and Sweepers.',
      '100+ migrations, stable production, years in operation — maintained schema evolution from initial July 2014 commit; managed editorial content via the BrowserCMS admin interface; deployed via Capistrano 2 + RVM on a MySQL-backed Rails 3.2.14 stack in long-running production.',
    ],
    outcome: 'FERATEL LIVE SYNC. 4 LOCALES.',
    tools: ['Rails 3.2', 'Ruby', 'MySQL', 'Globalize3', 'Sidekiq', 'Thinking Sphinx', 'GMaps4Rails', 'BrowserCMS', 'Paperclip', 'FFmpeg', 'Capistrano'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'left',
    imageUrl: 'images/ky.avif',
  },
  {
    date: '2014.Q2 — 2015.Q1',
    title: 'Operation: NOW',
    role: 'Software Engineer, Full-Stack',
    scanId: 'NWB-OPS-14',
    objective:
      'Discovering what\'s on in your city should feel instant — whether you\'re in Yakutsk, Moscow, or anywhere in between. Built the backend for a geo-aware events platform where MongoDB 2D indexes automatically detect your city from GPS coordinates, serve nearby events filtered by category, and cache content for three languages in Redis with 3-minute TTL — across a mobile REST API for iOS and Android clients.',
    tactics: [
      'Your city, detected automatically — modelled core domain in MongoDB/Mongoid ODM with 2D geospatial indexes on all location-aware documents for radius-based city auto-detection and proximity filtering across Events (news, concerts, discounts), Places, Cities, Categories, and Banners.',
      'A mobile API built for offline-ready clients — built a REST API (/api/customer/*) with device token authentication via Devise for iOS and Android, covering registration, login, city detection from coordinates, event/place listings, category filters, and user settings; serialized all responses via acts_as_api profile definitions.',
      'Three languages, served from cache — implemented a multilingual content layer (Russian, English, Yakut) using Mongoid localize: true for field-level document translations, backed by MongoDB-stored Translation documents and a Redis cache with 3-minute TTL for high-frequency locale lookups.',
      'Multi-tenant admin, city by city — enforced CanCan role hierarchy (super admin → city admin → controller → manager) with city-scoped ability definitions for multi-tenant admin access; mounted ActiveAdmin for full CRUD; managed Paperclip + ImageMagick image pipelines with five style variants (gallery, medium, thumb, small, logo).',
      'Web catalog and mobile API from one stack — delivered a multilingual web front-end (/:locale/* routing) for event and place catalogs, full-text search, contacts, and partner pages, backed by Redis session caching and a stable Rails 3.2.16 + MongoDB production stack.',
    ],
    outcome: 'GPS LOCATION DETECTED. 3 LOCALES.',
    tools: ['Rails', 'Ruby', 'MongoDB', 'Mongoid', 'Redis', 'Devise', 'ActiveAdmin', 'Sidekiq', 'Paperclip', 'ImageMagick'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'right',
    imageUrl: 'images/nwb.avif',
  },
  {
    date: '2013.Q1 — 2013.Q4',
    title: 'Operation: Scrij',
    role: 'Software Engineer, Full-Stack',
    scanId: 'SCR-OPS-13',
    objective:
      'Task management across iOS, Android, and web means GPS annotations, photo/video/audio attachments, team sharing, and a sync engine that can\'t miss a delta. Built a two-way sync platform that reconciles adds, updates, and deletes per device session without full payload re-fetches — with SuperTag geolocation, BaseResource STI media pipeline via Fog cloud storage, and APNS/GCM push notifications.',
    tactics: [
      'A domain hierarchy built for real-world collaboration — modelled User → Organization + Role → Todo (priority, dates, status, type) → SuperTag (lat/long/altitude) → BaseResource STI (photo/video/audio) → Comment with HABTM todo sharing and Contact linkage; tracked registered mobile clients via Scrijdevices (push token, UDID per user).',
      'Sync that catches every change across every device — engineered a two-way sync engine detecting adds, updates, and deletes across iOS, Android, and web clients, reconciling delta state per device session to keep all platforms consistent without full payload re-fetches; implemented /api namespace with Devise token auth and acts_as_api response profiles.',
      'Push that fires on the right events — integrated APNS push notifications via Grocer for iOS and GCM for Android, triggering alerts on todo assignment, status changes, and team activity; managed Scrijdevices token lifecycle for reliable delivery across client re-registrations.',
      'Every media type, cloud-stored and processed — built Paperclip + paperclip-ffmpeg media pipeline with Fog cloud storage for photo gallery, video transcoding, and audio clips across SuperTag annotations; rendered geo-located SuperTags on interactive Google Maps via gmaps4rails with calendar and dashboard views.',
      'Access control, admin panel, and deployment done right — enforced CanCan organization-scoped authorization (admin/manager/user) with Devise session auth for the web layer; delivered ActiveAdmin panel with Globalize3 multilingual support (EN/RU); deployed via Capistrano + RVM on MySQL-backed production.',
    ],
    outcome: 'MOBILE. WEB. DELTA IN SYNC.',
    tools: ['Rails', 'Ruby', 'MySQL', 'Devise', 'Grocer', 'GCM', 'Paperclip', 'FFmpeg', 'Fog', 'GMaps4Rails', 'CanCan', 'Capistrano'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'left',
    imageUrl: 'images/sk.avif',
  },
  {
    date: '2015.Q3 — 2016.Q3',
    title: 'Operation: Safety Sophite',
    role: 'Software Engineer, Full-Stack',
    scanId: 'SFTY-OPS-15',
    objective:
      'A home security platform has to broadcast alarms the moment they\'re triggered — to every trustee, with no polling, no delay. Built a white-label safety platform with Faye + Redis WebSocket alarm broadcasting, four-tier guardian permission tiers (NONE/VIEWER/MANAGER/MASTER), IoT device telemetry, multi-unit building management, and a 13-worker Sidekiq pipeline routing alerts through APNs, GCM, SMS, Email, and Facebook — deployed to AWS Elastic Beanstalk.',
    tactics: [
      '52 models spanning every safety scenario — modelled Alarm (send/cancel with shared location links), FollowMe (live location sharing sessions), Trustee (hierarchical guardian relationships with NONE/VIEWER/MANAGER/MASTER permission tiers), IMP IoT devices (battery, signal, temperature, humidity telemetry), MDU multi-unit buildings (floors, apartments, common areas, fire communities), and Organization for white-label tenant isolation.',
      '40+ endpoints, cleanly organized — delivered a REST API across 16 controllers organized into functional groups (auth, user, home, imp, trustee, alarm, follow_me, mdu, notification, system), all POST-based with auth_token header authentication layered on Devise for stateless mobile client access.',
      'Alarms broadcast instantly, no polling required — implemented real-time alarm and live location sharing via Faye + Redis pub/sub WebSocket channels; managed 13 Sidekiq workers + Sidekiq-Cron for async notification dispatch, scheduled safety checks, and IoT telemetry ingestion.',
      'Notifications reach every channel simultaneously — built a multi-channel pipeline routing alerts through APNs (Grocer) for iOS, GCM for Android, SMS, Email, and Facebook, triggered by Sidekiq workers on alarm events, trustee updates, and IoT threshold breaches; maintained Paperclip + AWS S3 for user media and device asset storage.',
      'AWS-deployed, production-hardened — deployed to AWS Elastic Beanstalk via Capistrano 3; maintained ActiveAdmin dashboard for operational oversight; backed by MySQL (primary data) + Redis (caching, sessions, pub/sub) across a HAML/SASS/CoffeeScript + jQuery frontend layer.',
    ],
    outcome: 'ALARMS. LIVE. INSTANT.',
    tools: ['Rails', 'Ruby', 'MySQL', 'Redis', 'Faye', 'Sidekiq', 'Grocer', 'GCM', 'Paperclip', 'AWS S3', 'AWS Elastic Beanstalk', 'Capistrano'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'right',
    imageUrl: 'images/sft.avif',
  },
  {
    date: '2016.Q2 — 2017.Q1',
    title: 'Operation: Taxi',
    role: 'Software Engineer, Full-Stack',
    scanId: 'STX-OPS-16',
    objective:
      'Ride-hailing in Ukraine means three API namespaces, four local payment gateways with SHA1 signature verification, and MongoDB finding the nearest driver in milliseconds. Built a tri-namespace backend for a mobile taxi service with 47 Mongoid models, geospatial near driver matching, a full order lifecycle state machine, and 13 Sidekiq workers handling push, SMS.ru, fee processing, and timeout cancellation.',
    tactics: [
      '47 models, every ride-hail scenario covered — modelled Customer, Driver, Order (multi-stop destinations, hot/cold types), Car, DriverLocation, DriverTransaction, Region, Rate, Feedback, and PushAlert with an order lifecycle state machine (open → accepted → in_progress → closed/canceled) and bidirectional rating flows.',
      'Three roles, three APIs, zero confusion — designed /api/customer/ for rider order placement and tracking, /api/driver/ for order acceptance and live location updates, and /api/dispatcher/ for operator-managed manual order placement and phone integration — each with scoped authentication and role-appropriate response contracts.',
      'Nearest driver matched before the user blinks — implemented MongoDB geospatial $near queries on DriverLocation documents for real-time proximity-based driver matching; maintained per-region pricing configuration (boarding fee + per-km rate, speed estimates, support contacts) for multi-city deployment.',
      'Four payment gateways, zero unverified callbacks — integrated Nonstop24, Citypay, Easysoft, and Privat24 alongside cash flow, all with SHA1 callback signature verification; built phone-based OTP auth (login11 flow) via Devise alongside Facebook and VKontakte (VK.com) social login for the Eastern European market.',
      '13 workers, every async task covered — operated Sidekiq + Sidekiq-Cron workers handling APNS/GCM push, SMS.ru and email dispatch, fee processing, order timeout auto-cancellation, and DriverLocation document cleanup; backed by Redis for sessions and caching; managed via ActiveAdmin with Russian/Ukrainian i18n.',
    ],
    outcome: 'RIDER. DRIVER. MATCHED.',
    tools: ['Rails', 'Ruby', 'MongoDB', 'Mongoid', 'Redis', 'Sidekiq', 'Devise', 'ActiveAdmin', 'APNS', 'GCM', 'SMS.ru'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'left',
    imageUrl: 'images/tx.avif',
  },
  {
    date: '2013.Q4 — 2014.Q3',
    title: 'Operation: TravelPlaces',
    role: 'Software Engineer, Full-Stack',
    scanId: 'TRP-OPS-13',
    objective:
      'Four Eastern European cities, five languages, two delivery targets — a public website and a mobile API with incremental sync — and one platform to serve them all. Built a subdomain-routed travel guide where each regional portal (Crimea, Donetsk, Batumi, Lviv) gets scoped layout and admin access, Globalize3 handles all translations at the DB level, and mobile clients sync only the delta they haven\'t seen — GPS-mapped, SEO-complete, and version-tracked.',
    tactics: [
      'Every region, its own experience — implemented subdomain-based multi-tenancy routing each portal (crimea/donetsk/batumi/lviv) to its scoped layout and content set, built on Place, Category, Region, Image, AdminUser, and Language models; managed Globalize3 DB-level translations across five locales (Russian, English, Ukrainian, Georgian, Polish) with Russian as default.',
      'Web and mobile from one data layer — delivered a public HomeController web interface (index, search, category browse, place detail with Kaminari pagination and SEO meta tags + sitemap) and a JSON REST APIController for mobile clients serving places, categories, and map data with version tracking for incremental sync.',
      'Every venue on the map, every image sized for the device — stored GPS coordinates on Place records and rendered interactive Google Maps via gmaps4rails; managed Paperclip image pipelines with mobile-optimized size variants (120×120 through 640×1136) to serve appropriately sized assets to web and native app clients.',
      'Admin access scoped to the region — enforced region-scoped ActiveAdmin access control restricting non-super-admins to their own region\'s content, with full CRUD for all editorial entities; built full-text search across place names and descriptions across the multilingual corpus.',
      'Bootstrap frontend, acts-as-api mobile, Capistrano deployed — delivered a Bootstrap 3 + jQuery + SASS/CoffeeScript frontend with acts-as-api response serialization for mobile endpoints; deployed via Capistrano + RVM on a MySQL-backed Rails 3.2 production stack.',
    ],
    outcome: 'CRIMEA. DONETSK. BATUMI. LVIV. SYNCED.',
    tools: ['Rails 3.2', 'Ruby', 'MySQL', 'Globalize3', 'GMaps4Rails', 'Paperclip', 'Bootstrap 3', 'jQuery', 'CoffeeScript', 'Capistrano'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'right',
    imageUrl: 'images/tv.avif',
  },
  {
    date: '2018.Q2 — 2019.Q4',
    title: 'Operation: Bible',
    role: 'Software Engineer, Full-Stack',
    scanId: 'WBS-OPS-18',
    objective:
      'Global Bible education at scale means state machines, event sourcing, and a teacher-student matching marketplace — across 70+ models and four languages. Built a DDD-influenced Rails 5.2 platform where every Assignment moves through a Statesman lifecycle from pending to Certificate generation, RailsEventStore captures every domain transition, and a Board marketplace lets teachers adopt students from an open queue — with Stripe congregation billing and 37 Pundit policies governing access.',
    tactics: [
      'A course completion engine that tracks every step — modelled the educational domain (Course → Exam → LessonSegment → Question → Choice) with STI (User → Student | Teacher) and Statesman state machines driving Assignment lifecycle (pending → started → completed → graded → reviewed → Certificate generation); backed by RailsEventStore event sourcing for a full audit trail.',
      'Teachers find students, students get matched — built a Board marketplace enabling teachers to adopt unassigned students from an open queue; implemented FollowupRequest spiritual workflows (baptism coordination, church introduction); managed campaign subdomain multi-tenancy for student acquisition channels (web, postal, referral) with per-campaign routing and analytics.',
      'API, i18n, and access control at global scale — delivered a REST API at /api/v1/ with JWT auth and JSON API serializers; maintained localized routes across four languages (EN/PT/ES/FR) with complete i18n coverage; enforced 37 Pundit RBAC policy files governing fine-grained access across all user roles.',
      'Billing, observability, and content delivery handled — integrated Stripe for group congregation billing with invoicing, subscription management, and campaign payment flows; managed AWS S3 + CarrierWave for course materials and certificates; wired Intercom for student support, Slack for internal alerts, New Relic for APM, and Cloudflare for edge performance.',
      'React for the future, jQuery for the present — delivered React 16 + Redux frontend modules via Webpacker alongside a legacy jQuery/CoffeeScript layer; operated 19 Sidekiq + Redis background workers for grading queues, mailer dispatch, and expiration workflows; deployed to Heroku production with Docker Compose local dev parity.',
    ],
    outcome: 'ENROLLED. EXAMINED. GRADED. CERTIFIED.',
    tools: ['Rails 5.2', 'Ruby', 'PostgreSQL', 'Statesman', 'React 16', 'Redux', 'Stripe', 'Sidekiq', 'Redis', 'Heroku', 'Docker', 'NewRelic', 'AWS S3', 'Intercom', 'Cloudflare'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'left',
    imageUrl: 'images/bb.avif',
  },
  {
    date: '2020.Q2 — 2022.Q4',
    title: 'Operation: Data Citadel',
    role: 'Full-Stack Engineer',
    scanId: 'DC-OPS-88',
    objective:
      'Reconstruct fragmented analytics infrastructure for a high-volume SaaS platform. Analysts across product, sales, and operations lacked reliable data pipelines to drive business decisions. Mandate: design a unified, distributed intelligence layer and expose it through clean, cross-team APIs — without disrupting live production.',
    tactics: [
      'Designed distributed event-driven pipelines feeding real-time cross-departmental dashboards, eliminating manual reporting.',
      'Delivered React-based internal tooling surfaces for order metrics, churn signals, and usage intelligence across four business units.',
      'Authored RESTful and GraphQL API contracts with clean, versioned schemas — adopted as the standard integration layer company-wide.',
    ],
    outcome: '4 UNITS UNIFIED',
    tools: ['React', 'GraphQL', 'REST API', 'PostgreSQL'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'right',
    isShield: true,
  },
  {
    date: '2017.Q1 — 2020.Q1',
    title: 'Operation: Foundation Layer',
    role: 'Software Engineer, Full Stack',
    scanId: 'FL-CORE-33',
    objective:
      'Rebuild frontend architecture for a growth-stage B2B platform whose jQuery monolith had become a hard blocker on feature velocity. Objective: migrate to a scalable, OOP-aligned component system with maintainable state management — while preserving shipping cadence.',
    tactics: [
      'Executed full migration from jQuery monolith to React, introducing Redux state management and a reusable component library.',
      'Implemented a CSS-in-JS (Emotion) design system, eliminating cross-squad style conflicts and accelerating UI delivery.',
      'Collaborated with the Rails backend team on shared API schema design, SQL/NoSQL query optimization, and integration test coverage.',
    ],
    outcome: '-70% TECH DEBT',
    tools: ['React', 'Redux', 'Emotion', 'Rails', 'PostgreSQL', 'SQL'],
    status: 'ARCHIVED',
    statusColor: 'text-white/40 bg-white/5',
    align: 'right',
    isGhost: true,
  },
];
